insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Mydeo', '544924115-1', 'Pennsylvania', 'Pittsburgh', 'Montana', 84);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Brainsphere', '362525888-9', 'Indiana', 'Evansville', 'Loeprich', 39);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Vinder', '576260117-X', 'California', 'Sacramento', 'Colorado', 95);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Devpulse', '303359246-5', 'Illinois', 'Chicago', 'Waubesa', 28);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Feedfire', '573787285-8', 'Indiana', 'South Bend', 'Manufacturers', 73);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Zoonoodle', '164971479-3', 'Virginia', 'Richmond', 'Westend', 99);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Centizu', '012209674-6', 'Massachusetts', 'Boston', 'Burrows', 73);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Omba', '689122253-2', 'New York', 'New York City', 'Dapin', 79);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('DabZ', '264846794-7', 'Texas', 'Houston', 'Erie', 51);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Tagcat', '283834304-1', 'Texas', 'Dallas', 'Pine View', 62);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Thoughtstorm', '596819475-8', 'Florida', 'Jacksonville', 'Merrick', 66);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Oyoba', '443280577-3', 'Iowa', 'Des Moines', 'Lunder', 66);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Lajo', '394262054-5', 'Florida', 'Jacksonville', 'Morningstar', 80);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Kazu', '640015177-X', 'Illinois', 'Chicago', 'Lyons', 41);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Dynava', '664018147-9', 'Delaware', 'Newark', 'Fairfield', 44);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Ainyx', '052483762-7', 'Missouri', 'Saint Louis', 'East', 10);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Twiyo', '940082805-5', 'California', 'Bakersfield', 'North', 85);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Twimm', '234507126-5', 'West Virginia', 'Charleston', 'Marcy', 70);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Trilia', '825701511-3', 'California', 'Sacramento', 'Bashford', 12);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Skaboo', '512019034-0', 'Arizona', 'Phoenix', 'Waubesa', 12);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Dabtype', '738673387-9', 'Texas', 'Dallas', 'Manley', 53);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Browsecat', '647315324-1', 'Mississippi', 'Biloxi', 'Dovetail', 90);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Quimba', '137208258-1', 'Louisiana', 'New Orleans', 'Thompson', 10);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Gigabox', '691192762-5', 'Ohio', 'Akron', 'Holmberg', 39);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Lazzy', '589352032-7', 'New Mexico', 'Albuquerque', 'Lotheville', 5);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Twitterworks', '224217897-0', 'Minnesota', 'Young America', 'Muir', 18);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Meevee', '667225072-7', 'Nevada', 'Las Vegas', 'Moland', 95);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Livefish', '327930638-8', 'Kentucky', 'Lexington', 'Mallory', 54);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Skynoodle', '137030053-0', 'Arkansas', 'Fort Smith', 'Grim', 85);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('BlogXS', '743113835-0', 'Colorado', 'Littleton', 'South', 39);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Zooxo', '883416749-X', 'California', 'Oceanside', 'Anderson', 41);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Wordify', '964019942-7', 'Illinois', 'Chicago', 'Fulton', 8);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Skynoodle', '469449977-7', 'North Dakota', 'Grand Forks', 'Kropf', 20);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Innojam', '440620587-X', 'Oklahoma', 'Norman', 'Kennedy', 83);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Jaloo', '263233440-3', 'Texas', 'San Antonio', 'Hoard', 23);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Dabshots', '153664485-4', 'Alabama', 'Tuscaloosa', 'Prentice', 95);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Photospace', '063502608-2', 'South Carolina', 'Columbia', 'Tomscot', 18);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Voomm', '021254515-9', 'Florida', 'Pinellas Park', 'Quincy', 80);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Browsecat', '149642464-6', 'North Carolina', 'Greensboro', 'Messerschmidt', 24);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Livetube', '131419823-8', 'California', 'San Jose', 'Alpine', 61);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Browsebug', '173487117-2', 'Michigan', 'Detroit', 'Truax', 99);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Dynazzy', '678174289-2', 'South Dakota', 'Sioux Falls', '1st', 97);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Photospace', '197736094-7', 'Alaska', 'Anchorage', 'School', 24);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Demivee', '151287484-1', 'Missouri', 'Kansas City', 'Dunning', 25);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('JumpXS', '495942428-1', 'Ohio', 'Akron', 'Maple', 40);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Jabberstorm', '683414627-X', 'Texas', 'El Paso', 'Grayhawk', 22);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Buzzster', '266955641-8', 'California', 'San Francisco', 'Corben', 91);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Wordtune', '291595397-X', 'Kansas', 'Shawnee Mission', 'Main', 71);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Brainsphere', '850396302-7', 'California', 'Long Beach', 'Scoville', 46);
insert into ristoranti (ragionesociale, piva, regione, citta, via, ncivico) values ('Jabberstorm', '781517240-7', 'North Carolina', 'Raleigh', 'Warrior', 85);
