insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('not applicable', 24.76, 4, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Gabapentin', 44.59, 4, 10);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('cetirizine hydrochloride', 35.16, 2, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate and Zinc Oxide', 41.3, 2, 44);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('diphenhydramine hydrochloride, menthol', 10.57, 1, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aralia Quinquefolia, Arnica Montana, Avena Sativa, Carduus Marianus, Dhea, Glandula Suprarenalis Suis, L-Arginine', 41.78, 3, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTSALATE, AVOBENZONE', 40.91, 3, 21);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', 18.9, 4, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Erythromycin', 9.23, 3, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Menthol', 17.55, 1, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ALCOHOL', 30.72, 1, 34);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('enoxaparin sodium', 37.39, 1, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydroxychloroquine sulfate', 19.56, 3, 9);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ampicillin sodium and sulbactam sodium', 45.9, 2, 32);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate, Octisalate, Octocrylene, and Zinc Oxide', 46.78, 2, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Arnica Montana, Rhus Toxicodendron, Dulcamara, Sanguinaria Canadensis, Cartilago Suis, Coenzyme A, Funiculus Umbilicalis Suis', 38.56, 1, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ethyl Alcohol', 33.46, 2, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ISOPROTERENOL HYDROCHLORIDE', 12.88, 4, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('TRAZODONE HYDROCHLORIDE, CHOLINE', 15.6, 4, 32);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Menthol', 45.33, 4, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Thuja Occidentalis', 21.23, 3, 23);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydrocortisone', 34.32, 2, 2);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Naphazoline hydrochloride, Polysorbate 80', 43.36, 4, 41);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('PAIN RELIEVING PLASTER', 44.84, 4, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('DOCUSATE SODIUM', 42.42, 3, 44);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('minocycline hydrochloride', 14.36, 1, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('bupropion hydrochloride', 35.33, 3, 24);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ACETAMINOPHEN, DEXTROMETHORPHAN HYDROBROMIDE, DOXYLAMINE SUCCINATE', 16.26, 1, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Citalopram Hydrobromide', 15.93, 3, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen, Diphenhydramine hydrochloride, Phenylephrine hydrochloride', 6.94, 1, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Omeprazole', 21.46, 4, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Carelessweed', 10.97, 4, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen, Dextromethorphan HBr, Phenylephrine HCl', 10.49, 3, 49);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('calcitriol', 39.14, 4, 10);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Arnica Montana', 38.91, 1, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Potassium Bicarbonate', 33.48, 4, 23);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dust, House Mixture', 8.7, 3, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ioxaglate meglumine and ioxaglate sodium', 21.51, 3, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Atenolol', 21.39, 4, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Paecilomyces', 30.02, 4, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextromethorphan HBr, Guaifenesin', 39.46, 4, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Clarithromycin', 28.62, 2, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('BENZETHONIUM CHLORIDE', 16.76, 4, 42);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dronabinol', 15.71, 3, 21);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('carbidopa, levodopa and entacapone', 34.7, 4, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Rough Marsh Elder', 40.28, 3, 16);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Polyvinyl Alcohol and Povidone', 6.12, 3, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ibuprofen', 27.35, 2, 49);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ovarium 6 Special Order', 24.2, 1, 18);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Methimazole', 20.85, 2, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('MORPHINE SULFATE', 36.94, 1, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('HOMOSALATE, OCTISALATE, OCTOCRYLENE', 32.45, 2, 18);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Anthracinum, Pyrogenium, Aconitum nap., Aloe, Apis mel., Arnica, Arsenicum alb., Baptisia, Belladonna, Bryonia, Cantharis, Chelidonium majus, Crotalus horridus, Ferrum phosphoricum, Gaultheria procumbens, Hepar sulph. calc., Iodium, Lachesis, Nux vom., Phosphorus, Pulsatilla, Rhus toxicodendron, Veratrum viride, Verbascum, Echinacea', 32.13, 3, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Sulfamethoxazole and Trimethoprim', 8.02, 4, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTINOXATE, OXYBENZONE, TITANIUM DIOXIDE', 40.77, 2, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Minoxidil', 12.8, 4, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('PNV Ferrous Fumarate Docusate Folic Acid', 34.54, 3, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate', 12.27, 1, 2);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Salicylic Acid', 44.39, 2, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('acetaminophen, dextromethorphan Hbr, Phenylephrine HCl', 28.35, 2, 9);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Metoprolol Succinate', 38.91, 4, 23);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Macrodantin', 35.93, 1, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Carvedilol', 6.8, 2, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Antihemophilic Factor, Human Recombinant', 17.29, 2, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextrose monohydrate', 17.11, 4, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ciprofloxacin', 14.85, 4, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen, Dextromethorphan HBr', 6.38, 1, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Bicalutamide', 5.11, 2, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Gentian Violet 2%', 15.02, 1, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('norgestimate and ethinyl estradiol', 27.63, 2, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Captopril', 20.91, 1, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('guanfacine', 40.12, 3, 40);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Amoxicillin', 37.24, 1, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ciprofloxacin', 8.08, 3, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Alcohol', 21.39, 1, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate ,Meradimate', 46.01, 2, 2);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('GEMFIBROZIL', 15.34, 3, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Mineral Oil', 14.95, 1, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Medicated Corn Removers', 46.85, 4, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Glycerin, Hypromellose, Polyethylene glycol 400', 7.39, 1, 23);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Estradiol Transdermal System', 19.94, 2, 23);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Menthol and Methyl Salicylate', 49.0, 3, 31);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('alcohol', 36.1, 4, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('AMMONIUM LACTATE', 20.11, 2, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aspirin', 28.3, 4, 22);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Zinc oxide', 31.3, 1, 24);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lidocaine', 39.72, 4, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Nadolol', 15.99, 3, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextromethorphan Hydrobromide, Guaifenesin, Phenylephrine Hydrochloride', 26.45, 1, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('PROGESTERONE', 38.75, 1, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Antimonium tartaricum, Echinacea angustifolia, Euphorbium officinarum, Hepar sulphuris calcareum, Hepatica tribola, Hydrastis canadensis, Mercurius sulfuratus ruber, Natrum muriaticum, Phosphorus', 23.3, 4, 16);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Atenolol and Chlorthalidone', 20.87, 2, 15);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ibuprofen', 7.43, 2, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ibuprofen', 12.55, 4, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aspirin', 21.74, 4, 49);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('acetaminophen, dextromethorphan hydrobromide and doxylamine succinate', 39.76, 1, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydrocortisone', 26.7, 1, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Couch Quack Grass', 35.1, 3, 21);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydromorphone HCl', 32.93, 2, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('LIDOCAINE HYDROCHLORIDE ANHYDROUS and DEXTROSE MONOHYDRATE', 17.76, 3, 23);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Isopropyl Alcohol', 28.2, 3, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('SALICYLIC ACID', 42.95, 2, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('verapamil hydrochloride', 43.13, 3, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Alcohol', 30.32, 2, 10);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('dexlansoprazole', 5.14, 4, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Warfarin Sodium', 30.23, 4, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTINOXATE, OCTOCRYLENE, and TITANIUM DIOXIDE', 40.95, 4, 9);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Carisoprodol', 35.1, 3, 18);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('DEXTROSE MONOHYDRATE', 23.13, 4, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Menthol', 43.45, 4, 16);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Heart Muscle Aid', 16.82, 1, 18);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Allergenic Extracts Alum Precipitated', 21.63, 3, 8);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('oxacillin', 41.19, 3, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Triamterene and Hydrochlorothiazide', 18.95, 2, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ibuprofen', 33.69, 2, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen, Doxylamine succinate, Phenylephrine Hydrochloride', 49.36, 2, 16);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('AZITHROMYCIN', 27.61, 1, 32);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate, Avobenzone and Octisalate', 37.81, 2, 10);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ZINC OXIDE', 15.75, 1, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('BENZALKONIUM CHLORIDE', 10.67, 2, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('dasatinib', 6.77, 4, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Folic Acid', 34.74, 1, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('mentha piperita', 11.39, 3, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('SODIUM CHLORIDE, SODIUM LACTATE, POTASSIUM CHLORIDE, and CALCIUM CHLORIDE', 46.53, 4, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 20.24, 4, 49);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Simvastatin', 6.57, 4, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTINOXATE', 9.77, 2, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Latrodectus mactans', 29.94, 4, 31);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Tadalafil', 41.48, 1, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('DOCUSATE SODIUM', 32.08, 1, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ibuprofen', 41.63, 3, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lorazepam', 16.89, 3, 15);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('cisatracurium besylate', 28.75, 4, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Avobenzone, Homosalate, Octisalate and Octocrylene', 44.27, 4, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Avobenzone Octisalate Octocrylene', 19.93, 3, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen', 20.08, 4, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Immunodoron', 49.92, 2, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Moexipril hydrochloride and hydrochlorothiazide', 8.41, 1, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('zolpidem tartrate', 23.07, 3, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Garlic', 49.65, 2, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('AVOBENZONE, OCTINOXATE, OCTISALATE, OXYBENZONE', 5.15, 4, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lisinopril and Hydrochlorothiazide', 32.45, 3, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTOCRYLENE, OCTINOXATE, TITANIUM DIOXIDE', 20.89, 3, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Fluocinonide', 45.17, 4, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Isopropyl Alcohol', 28.4, 1, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('BENZALKONIUM CHLORIDE', 37.66, 2, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aluminum Sesquichlorohydrate', 33.96, 4, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Brome Grass', 39.6, 3, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Levothyroxine Sodium', 49.3, 4, 9);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ECHINACEA ANGUSTIFOLIA, ECHINACEA PURPUREA, ACONITUM NAPELLUS, ARNICA MONTANA, CALENDULA OFFICIANALIS, HAMAMELIS VIRGINIANA, BELLADONNA, BELLIS PERENNIS, CHAMOMILLIA, MILLEFOLIUM, HYPERICUM PERFORATUM, SYMPHYTUM OFFICINALE, COLCHICINUM, ZINGIBER OFFICINALE', 39.85, 3, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextromethorphan, Guaifenesin, Phenylephrine', 36.14, 2, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Throat Spray', 23.75, 2, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Pecan Carya Carya illinoensis', 15.74, 4, 24);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Salicylic Acid', 14.11, 2, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Diltiazem Hydrochloride', 22.68, 2, 24);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Mineral Oil', 22.23, 1, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lidocaine Hydrochloride', 8.6, 2, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Phenytoin Sodium', 26.26, 3, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('CARVEDILOL', 8.32, 1, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dexamethasone Sodium Phosphate', 25.53, 4, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 25.82, 3, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Loratadine', 6.24, 1, 21);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate', 5.42, 3, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Menthol and Camohor (synthetic)', 26.25, 3, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('AVOBENZONE HOMOSALATE OCTISALATE OCTOCRYLENE', 46.01, 2, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Diltiazem Hydrochloride', 24.06, 4, 8);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Niacin', 24.56, 4, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('octinoxate, octisalate, octocrylene, oxybenzone', 22.49, 4, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Methyl Salicylate, Camphor, Menthol', 42.89, 4, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('HYDROQUINONE', 21.88, 2, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('GABAPENTIN', 42.48, 1, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('metoprolol tartrate', 10.06, 4, 35);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Oxygen', 29.22, 3, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('CAIRINA MOSCHATA HEART/LIVER AUTOLYSATE', 26.08, 2, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('lorazepam', 11.85, 3, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Calcarea carbonica, Calcarea Fluorica, Calcarea phosphorica, Hekla lava, Hydrofluoricum acidum, Magnesia phosphorica Rhus toxicodendron, Ruta graveolens, Silicea, Symphytum officinale', 25.91, 4, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Oyster', 16.02, 2, 41);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ROPIVACAINE HYDROCHLORIDE', 15.58, 4, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('butalbital, acetaminophen and caffeine', 5.87, 1, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ISOPROPYL ALCOHOL', 17.6, 3, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('fibrinogen human and thrombin human', 13.92, 4, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Apis ex animale 30', 38.23, 1, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Deferoxamine Mesylate', 39.37, 4, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextromethorphan Hydrobromide and Guaifenesin', 38.7, 2, 24);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lisinopril and Hydrochlorothiazide', 15.96, 3, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Water', 20.11, 2, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('octinoxate, octisalate', 19.64, 4, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen and Codeine Phosphate', 11.8, 1, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('White Oak', 35.75, 1, 15);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Treatment Set TS350242', 41.19, 2, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('repaglinide', 5.18, 2, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('acyclovir', 42.37, 2, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('enoxaparin sodium', 7.17, 4, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Fluoride Toothpaste', 43.15, 4, 42);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hepatitis A Vaccine', 14.08, 3, 8);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('DOCUSATE SODIUM', 38.43, 1, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('risperidone', 38.7, 2, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Chlorpheniramine Maleate, Pseudoephedrine Hydrochloride', 36.31, 4, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Alprazolam', 34.91, 1, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Russian Thistle', 7.08, 1, 31);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Triclosan', 49.26, 3, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('octinoxate, octisalate, zinc oxide, oxybenzone,', 25.37, 1, 22);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Famotidine, Calcium carbonate, and Magnesium hydroxide', 6.3, 3, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('oxacillin sodium', 48.37, 1, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('bexarotene', 36.18, 2, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lovastatin', 26.98, 2, 21);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('enoxaparin sodium', 34.22, 1, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('risperidone', 31.67, 2, 50);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ciclopirox', 21.37, 1, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Perphenazine', 8.94, 2, 22);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ALLANTOIN', 5.65, 4, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Felodipine', 44.07, 4, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Bryonia , Cocculus, Gelsemium, Lobelia inf, Acacia gum, lactose, magnesium stearate, corn starch, sucrose', 37.14, 2, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydromorphone HCl', 20.91, 2, 49);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('desipramine hydrochloride', 41.95, 3, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('VANCOMYCIN HYDROCHLORIDE', 12.79, 4, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTINOXATE, OXYBENZONE, PADIMATE O', 28.75, 3, 15);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('pazopanib hydrochloride', 15.09, 2, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Simethicone', 7.98, 4, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen, Phenylephrine HCl and Dextromethorphan HBr', 17.79, 2, 34);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Androstenedione, Dehydroepiandrosterone, Pregenolone, Progesterone, Testosterone', 35.08, 1, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('CALCIUM FLUORIDE, TRIBASIC CALCIUM PHOSPHATE, CALCIUM SULFATE ANHYDROUS, FERROSOFERRIC PHOSPHATE, POTASSIUM CHLORIDE, POTASSIUM PHOSPHATE, DIBASIC, POTASSIUM SULFATE, MAGNESIUM PHOSPHATE, DIBASIC TRIHYDRATE, SODIUM CHLORIDE, SODIUM PHOSPHATE, DIBASIC, HEPTAHYDRATE, SODIUM SULFATE, and SILICON DIOXIDE', 46.31, 2, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Neomycin Sulfate', 18.89, 2, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OXYGEN', 36.41, 3, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('cocoa butter, phenylephrine HCl', 49.43, 3, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('APIS MELLIFERA - CARBON DISULFIDE - PULSATILLA VULGARIS - SILICON DIOXIDE - DELPHINIUM STAPHISAGRIA SEED -', 13.63, 1, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Nicotine Polacrilex', 40.92, 3, 49);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate', 43.71, 1, 2);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextromethorphan HBr, Guaifenesin', 22.13, 3, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aluminum Zirconium Octachlorohydrex Gly', 42.75, 1, 50);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Zinc Oxide', 35.96, 2, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ALUMINUM HYDROXIDE, BISMUTH SUBCARBONATE, CALCIUM CARBONATE, MAGNESIUM CARBONATE, SODIUM BICARBONATE', 43.89, 4, 39);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Oxymetazoline hydrochloride', 33.66, 2, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Sotalol Hydrochloride', 21.83, 2, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('isosorbide mononitrate', 43.82, 4, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Diphenhydramine HCl and Pramoxine HCl', 28.94, 1, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Treatment Set TS345784', 22.56, 2, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('TITANIUM DIOXIDE', 42.33, 2, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate, Octisalate, and Oxybenzone', 21.74, 3, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Amoxicillin', 17.24, 1, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydrocodone Bitartrate and Acetaminophen', 20.69, 3, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Zinc Oxide and Titanium dioxide', 11.63, 4, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('amitriptyline hydrochloride', 11.18, 1, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lovastatin', 49.57, 2, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Enalapril Maleate', 11.54, 1, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ST JOHNS WORT', 32.75, 3, 8);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aspirin', 24.34, 3, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Triclosan', 22.65, 1, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Levetiracetam', 10.92, 4, 24);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('HYPERICUM,ARNICA,SYMPHYTUM OFFICINALE, BELLIS PERENNIS, STAPHYSAGRIA', 18.76, 4, 16);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydrochlorothiazide', 15.58, 4, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aconite 30c, Arsenicum 30c, Bambusa 30c, Baryta Carb 30c, Calc Carb 30c, Calc Phos 30c, Hyoscyamus 30c, Ignatia 30c, Lilium Tig 30c, Lycopodium 30c, Mag Mur 30c, Nat Mur 30c,Nat Sulph 30c, Nux Vomica 30c, Phosphorous 30c, Sepia 30c, Silicea 30c, Staphysagria 30c, Stramonium', 23.89, 3, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Methylprednisolone', 23.05, 2, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('aluminum hydroxide and magnesium carbonate', 5.56, 4, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen', 16.44, 2, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Cefdinir', 43.13, 3, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Sumatriptan Succinate', 8.9, 4, 44);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ampicillin sodium', 24.25, 4, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTINOXATE and TITANIUM DIOXIDE', 44.97, 2, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('TOPICAL STARCH', 8.12, 1, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lidocaine', 14.77, 3, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ritonavir', 44.78, 1, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Besifloxacin', 13.32, 2, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Mupirocin', 12.81, 4, 40);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('etravirine', 46.3, 3, 9);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('clindamycin phosphate', 24.18, 3, 27);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aloe Socotrina, Alumina, Apis Mellifica, Arsenicum Album, Baryta Carbonica, Bryonia, Carbo Vegetabilis, Chamomilla', 36.87, 3, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ciprofloxacin', 32.43, 3, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Insulin', 7.35, 3, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('IRBESARTAN AND HYDROCHLOROTHIAZIDE', 30.15, 1, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Caffeine', 35.34, 2, 34);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('mycophenolate mofetil', 34.1, 2, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('COAGULATION FACTOR IX (HUMAN)', 30.9, 3, 50);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('sumatriptan succinate', 8.91, 1, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('octocrylene, octisalate, avobenzone', 30.73, 2, 32);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('enalaprilat', 37.5, 3, 8);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('TITANIUM DIOXIDE', 39.73, 3, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Benazepril Hydrochloride and Hydrochlorothiazide', 42.65, 2, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aluminum Zirconium Tetrachlorohydrex GLY', 9.38, 4, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Benzonatate', 8.36, 3, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Hydralazine Hydrochloride', 15.73, 4, 23);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Benzocaine', 5.79, 3, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('RUTA GRAVEOLENS FLOWERING TOP', 23.91, 2, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('lamotrigine', 30.78, 2, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('RIVASTIGMINE TARTRATE', 31.24, 1, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Sodium fluoride', 36.67, 3, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Oxygen', 39.6, 3, 34);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Leucine, Phenylalanine, Lysine, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Serine, Tyrosine, Sodium Acetate, Dibasic Potassium Phosphate, Ma', 37.63, 4, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Glycerin', 22.17, 2, 7);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('dexamethasone', 36.06, 1, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Glipizide and Metformin HCl', 20.0, 2, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ginkgo biloba leaf', 23.56, 2, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Wheat Smut', 12.04, 2, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('penicillium glabrum', 5.1, 4, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Carbamazepine', 46.75, 1, 35);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('losartan potassium', 5.91, 1, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Phenylephrine Hydrochloride', 25.71, 4, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ethyl Alcohol', 25.8, 1, 47);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Bupropion Hydrochloride', 29.43, 2, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('SODIUM FLUORIDE', 48.15, 4, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Benzocaine', 7.13, 1, 22);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Warfarin Sodium', 23.29, 1, 10);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Amlodipine Besylate', 31.89, 3, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ethambutol hydrochloride', 17.92, 2, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Lisinopril', 26.9, 2, 21);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('DIMENHYDRINATE', 13.3, 2, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Octinoxate, Octocrylene, Titanium Dioxide, Zinc Oxide', 23.51, 2, 18);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Short Ragweed Pollen', 30.13, 1, 42);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dexamethasone Sodium Phosphate', 7.0, 1, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('RABEPRAZOLE SODIUM', 33.35, 4, 39);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('White Petroleum', 39.99, 2, 31);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('perphenazine and amitriptyline hydrochloride', 25.68, 4, 41);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Naproxen sodium', 21.42, 4, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Nitroglycerin', 8.19, 3, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Guaifenesin and Dextromethorphan Hydrobromide', 47.83, 2, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Minocycline Hydrochloride', 49.17, 4, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OXYGEN', 41.5, 4, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('MENTHOL', 46.72, 4, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Imipramine Hydrochloride', 33.33, 3, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Albumin (Human)', 26.82, 2, 34);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Poa pratensis', 47.53, 2, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Tinidazole', 16.87, 2, 44);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Gemfibrozil', 46.46, 4, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('MIRTAZAPINE', 24.8, 2, 12);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Docusate Sodium', 20.01, 1, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('nifedipine', 14.92, 3, 9);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Gabapentin', 23.48, 1, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Calcium Carbonate and Vitamin D3', 33.19, 4, 37);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ACETAMINOPHEN, DEXTROMETHORPHAN HBr, GUAIFENESIN, PSEUDOEPHEDRINE HCl', 36.72, 2, 3);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Pseudoephedrine Hydrochloride', 29.71, 2, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aluminum Chlorohydrate', 10.8, 3, 40);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('galphimia glauca flowering top, histamine dihydrochloride, luffa operculata fruit, and sulfur', 48.66, 1, 8);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('tolbutamide', 17.62, 4, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ethyl Alcohol', 33.4, 2, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Allergenic Extracts Alum Precipitated', 42.83, 3, 33);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('EUCALYPTOL', 6.21, 1, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Bethanechol Chloride', 33.65, 2, 31);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('DIPHENHYDRAMINE HYDROCHLORIDE', 44.19, 2, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Phenylephrine Hydrochloride, Hydrogenate Palm Kernel Oil', 32.31, 2, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('magnesium sulfate', 23.49, 3, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Sulindac', 14.12, 4, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aluminum Oxide 30C, Silver Nitrate 30C, Berberis Vulgaris Fruit 30C, Conium Maculatum Flowering Top 30C, Iron 30C, Gelsemium Sempervirens Root 30C, Guaiacum Officinale Resin 30C, Hydrogen 30C, Lachesis Muta Venom 30C, Phosphoric Acid 30C, Toxicodendron Pubescens Leaf 30C', 12.99, 3, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Chelidonium majus, Echinacea (angustifolia), Hydrastis canadensis, Nasturtium aquaticim, Taraxacum officinale, Trifolium pratense, Urtica dioica,', 30.74, 4, 39);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Titanium Dioxide', 13.97, 3, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Glimepiride', 17.81, 2, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextrose Monohydrate, Sodium Chloride, Calcium Chloride, Magnesium Chloride, Sodium Lactate', 29.15, 2, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Levothyroxine Sodium', 38.81, 3, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Camphor, Menthol, Methyl Salicylate', 6.84, 3, 15);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ramipril', 42.24, 3, 18);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Water Hemp', 20.61, 2, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Acetaminophen', 47.41, 3, 2);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Aconite 30C, Belladonna 30C, Chamomilla 30C, Phytolacca 30C', 29.71, 4, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ESZOPICLONE', 25.93, 3, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Duloxetine hydrochloride', 34.44, 4, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Sulfacetamide Sodium and Sulfur', 23.22, 2, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Methocarbamol', 36.64, 2, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Diphenhydramine Hydrochloride', 49.66, 4, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Atenolol and Chlorthalidone', 24.37, 3, 10);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('ATP (adenosine triphosphate disodium), Coenzyme A, Co-enzyme Q-10, Pineal gland (suis), Sarcolacticum acidum, Melatonin, Pyrrole, Tryptophan,', 42.95, 1, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('TITANIUM DIOXIDE, ZINC OXIDE', 19.95, 3, 16);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Megestrol Acetate', 6.94, 3, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('PROMETHAZINE HYDROCHLORIDE', 21.59, 2, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Guaifenesin', 41.71, 3, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Topiramate', 22.91, 4, 17);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTISALATE, OXYBENZONE, and AVOBENZONE', 18.71, 2, 25);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('GLYCERIN', 30.79, 1, 1);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('nifedipine', 20.43, 3, 41);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Estradiol', 6.05, 1, 46);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Thyreoidea Melissa', 31.67, 4, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Propranolol Hydrochloride', 32.86, 3, 19);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Naproxen Sodium', 34.18, 4, 13);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('TITANIUM DIOXIDE', 45.39, 2, 34);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('SALICYLIC ACID', 9.24, 2, 30);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('phytonadione', 7.84, 3, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Diphenhydramine HCl', 37.95, 2, 44);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Miconazole nitrate', 38.87, 1, 22);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Ethosuximide', 35.77, 1, 28);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Famotidine', 17.1, 3, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Albuterol Sulfate', 47.1, 4, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Centella Asiatica, Gentiana Lutea Root, Sambucus Niger Flowering Top, Arsenic Trioxide, Bismuth Subnitrate, Activated Charcoal, Potassium Dichromate, Lycopodium Clavatium Spore, Strychnos Nux-Vomica Seed, Phosphorus, Pulsatilla VulgarisPhosphorus, Pulsatilla Vulgaris', 42.63, 2, 5);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Miconazole Nitrate', 49.29, 4, 16);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('risperidone', 28.09, 4, 43);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('SIMVASTATIN', 32.98, 2, 4);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('OCTINOXATE and TITANIUM DIOXIDE', 9.88, 4, 50);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Benzocaine', 16.64, 2, 20);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('olsalazine sodium', 32.44, 1, 48);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('lisdexamfetamine dimesylate', 41.82, 4, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Flores Formica', 8.47, 1, 11);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('GLYCERIN', 17.47, 2, 9);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Agaricus musc., Arsenicum alb., Aur. met, Berber. aqui., Caladium seguinum, Candida albicans, Cantharis, Conium, Graphites, Helonias dioica, Hydrastis, Kali carb., Kreosotum, Lycopodium, Merc. viv., Murex purpurea, Nat. mur, Nitricum ac., Pulsatilla, Rhus toxicodendron, Sepia, Sulphur, Tarentula hispana, Thuja occ., Zinc. met., Apis mel, Hamamelis', 10.04, 1, 31);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('lamotrigine', 20.43, 3, 29);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Dextromethorphan, Guiafenesin, Pseudoephedrine HCl', 17.97, 1, 38);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('morphine sulfate', 13.49, 1, 6);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('propolis', 30.02, 2, 35);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('dimethyl fumarate', 11.98, 1, 26);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Meteoric Iron Prunus', 38.61, 4, 44);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Mineral oil, petrolatum, phenylephrine hcl', 43.43, 3, 14);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Oxybutynin', 20.43, 2, 36);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('pantoprazole sodium', 37.73, 1, 45);
insert into piatti (nome, prezzo, categoria_id, ristorante_id) values ('Eszopiclone', 21.4, 4, 33);
