insert into ingredienti (nome, piatto_id) values ('Nescafe - Frothy French Vanilla', 271);
insert into ingredienti (nome, piatto_id) values ('Skewers - Bamboo', 68);
insert into ingredienti (nome, piatto_id) values ('Steam Pan - Half Size Deep', 378);
insert into ingredienti (nome, piatto_id) values ('Chutney Sauce', 233);
insert into ingredienti (nome, piatto_id) values ('Hold Up Tool Storage Rack', 159);
insert into ingredienti (nome, piatto_id) values ('Wine - Malbec Trapiche Reserve', 378);
insert into ingredienti (nome, piatto_id) values ('Prunes - Pitted', 166);
insert into ingredienti (nome, piatto_id) values ('Pike - Frozen Fillet', 221);
insert into ingredienti (nome, piatto_id) values ('Wine - Magnotta - Cab Franc', 271);
insert into ingredienti (nome, piatto_id) values ('Wine - Carmenere Casillero Del', 242);
insert into ingredienti (nome, piatto_id) values ('Sour Puss Raspberry', 276);
insert into ingredienti (nome, piatto_id) values ('Wine - Taylors Reserve', 82);
insert into ingredienti (nome, piatto_id) values ('Soup - Chicken And Wild Rice', 345);
insert into ingredienti (nome, piatto_id) values ('Wine - Jackson Triggs Okonagan', 379);
insert into ingredienti (nome, piatto_id) values ('Bag - Clear 7 Lb', 107);
insert into ingredienti (nome, piatto_id) values ('Grapes - Black', 340);
insert into ingredienti (nome, piatto_id) values ('Pork - Back, Short Cut, Boneless', 367);
insert into ingredienti (nome, piatto_id) values ('Tortillas - Flour, 8', 277);
insert into ingredienti (nome, piatto_id) values ('Tabasco Sauce, 2 Oz', 145);
insert into ingredienti (nome, piatto_id) values ('Shopper Bag - S - 4', 214);
insert into ingredienti (nome, piatto_id) values ('Pasta - Penne, Lisce, Dry', 76);
insert into ingredienti (nome, piatto_id) values ('Fish - Halibut, Cold Smoked', 144);
insert into ingredienti (nome, piatto_id) values ('Steampan Lid', 27);
insert into ingredienti (nome, piatto_id) values ('Soup - Cream Of Broccoli, Dry', 179);
insert into ingredienti (nome, piatto_id) values ('Bag Clear 10 Lb', 289);
insert into ingredienti (nome, piatto_id) values ('Sour Puss Raspberry', 118);
insert into ingredienti (nome, piatto_id) values ('Stock - Veal, Brown', 99);
insert into ingredienti (nome, piatto_id) values ('Sausage - Chorizo', 5);
insert into ingredienti (nome, piatto_id) values ('Muffin Batt - Carrot Spice', 349);
insert into ingredienti (nome, piatto_id) values ('Wine - Piper Heidsieck Brut', 342);
insert into ingredienti (nome, piatto_id) values ('Quail - Eggs, Fresh', 58);
insert into ingredienti (nome, piatto_id) values ('Beans - Soya Bean', 167);
insert into ingredienti (nome, piatto_id) values ('Gelatine Leaves - Bulk', 222);
insert into ingredienti (nome, piatto_id) values ('Sauce - Thousand Island', 301);
insert into ingredienti (nome, piatto_id) values ('Grenadillo', 155);
insert into ingredienti (nome, piatto_id) values ('Wine - Puligny Montrachet A.', 135);
insert into ingredienti (nome, piatto_id) values ('Tortillas - Flour, 8', 289);
insert into ingredienti (nome, piatto_id) values ('Tea - Lemon Scented', 75);
insert into ingredienti (nome, piatto_id) values ('Iced Tea - Lemon, 460 Ml', 279);
insert into ingredienti (nome, piatto_id) values ('Tamarind Paste', 258);
insert into ingredienti (nome, piatto_id) values ('Muffin Chocolate Individual Wrap', 154);
insert into ingredienti (nome, piatto_id) values ('Octopus - Baby, Cleaned', 249);
insert into ingredienti (nome, piatto_id) values ('Ranchero - Primerba, Paste', 328);
insert into ingredienti (nome, piatto_id) values ('Lamb - Shoulder, Boneless', 326);
insert into ingredienti (nome, piatto_id) values ('Fiddlehead - Frozen', 274);
insert into ingredienti (nome, piatto_id) values ('Edible Flower - Mixed', 343);
insert into ingredienti (nome, piatto_id) values ('Soup - Knorr, Ministrone', 277);
insert into ingredienti (nome, piatto_id) values ('Lamb Rack - Ontario', 127);
insert into ingredienti (nome, piatto_id) values ('Appetizer - Smoked Salmon / Dill', 377);
insert into ingredienti (nome, piatto_id) values ('Paper Cocktail Umberlla 80 - 180', 98);
insert into ingredienti (nome, piatto_id) values ('Fish - Soup Base, Bouillon', 289);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Chardonnay', 173);
insert into ingredienti (nome, piatto_id) values ('Chocolate - Dark', 363);
insert into ingredienti (nome, piatto_id) values ('Baking Powder', 15);
insert into ingredienti (nome, piatto_id) values ('Beer - Molson Excel', 282);
insert into ingredienti (nome, piatto_id) values ('Soup Campbells Beef With Veg', 392);
insert into ingredienti (nome, piatto_id) values ('Urban Zen Drinks', 205);
insert into ingredienti (nome, piatto_id) values ('Bread - Rolls, Rye', 316);
insert into ingredienti (nome, piatto_id) values ('Wine - George Duboeuf Rose', 246);
insert into ingredienti (nome, piatto_id) values ('Truffle Cups Green', 127);
insert into ingredienti (nome, piatto_id) values ('Orange - Tangerine', 117);
insert into ingredienti (nome, piatto_id) values ('Island Oasis - Lemonade', 279);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Concha Y Toro', 108);
insert into ingredienti (nome, piatto_id) values ('Vinegar - Balsamic, White', 49);
insert into ingredienti (nome, piatto_id) values ('Pork - Tenderloin, Frozen', 376);
insert into ingredienti (nome, piatto_id) values ('Bar Mix - Lime', 234);
insert into ingredienti (nome, piatto_id) values ('Sherbet - Raspberry', 353);
insert into ingredienti (nome, piatto_id) values ('Coconut Milk - Unsweetened', 129);
insert into ingredienti (nome, piatto_id) values ('Lady Fingers', 226);
insert into ingredienti (nome, piatto_id) values ('Doilies - 12, Paper', 219);
insert into ingredienti (nome, piatto_id) values ('Compound - Mocha', 104);
insert into ingredienti (nome, piatto_id) values ('Wine - White Cab Sauv.on', 232);
insert into ingredienti (nome, piatto_id) values ('Tomatillo', 125);
insert into ingredienti (nome, piatto_id) values ('Coffee Swiss Choc Almond', 194);
insert into ingredienti (nome, piatto_id) values ('Table Cloth 62x120 White', 2);
insert into ingredienti (nome, piatto_id) values ('Wine - Magnotta - Pinot Gris Sr', 18);
insert into ingredienti (nome, piatto_id) values ('Quail - Jumbo', 72);
insert into ingredienti (nome, piatto_id) values ('Glucose', 230);
insert into ingredienti (nome, piatto_id) values ('Sugar - Cubes', 64);
insert into ingredienti (nome, piatto_id) values ('Sprouts - Alfalfa', 94);
insert into ingredienti (nome, piatto_id) values ('Pork - Ham, Virginia', 340);
insert into ingredienti (nome, piatto_id) values ('Shrimp - 150 - 250', 229);
insert into ingredienti (nome, piatto_id) values ('Sobe - Cranberry Grapefruit', 122);
insert into ingredienti (nome, piatto_id) values ('Filter - Coffee', 381);
insert into ingredienti (nome, piatto_id) values ('Sole - Dover, Whole, Fresh', 392);
insert into ingredienti (nome, piatto_id) values ('Grenadine', 215);
insert into ingredienti (nome, piatto_id) values ('Bread - Onion Focaccia', 137);
insert into ingredienti (nome, piatto_id) values ('Pickles - Gherkins', 151);
insert into ingredienti (nome, piatto_id) values ('Bread - Mini Hamburger Bun', 190);
insert into ingredienti (nome, piatto_id) values ('Rambutan', 144);
insert into ingredienti (nome, piatto_id) values ('Beef - Ground Lean Fresh', 116);
insert into ingredienti (nome, piatto_id) values ('Wine - Ej Gallo Sonoma', 216);
insert into ingredienti (nome, piatto_id) values ('Bagel - 12 Grain Preslice', 322);
insert into ingredienti (nome, piatto_id) values ('Syrup - Monin, Amaretta', 269);
insert into ingredienti (nome, piatto_id) values ('Pineapple - Golden', 387);
insert into ingredienti (nome, piatto_id) values ('Pork - Backfat', 277);
insert into ingredienti (nome, piatto_id) values ('Tomatoes', 354);
insert into ingredienti (nome, piatto_id) values ('Garlic - Peeled', 113);
insert into ingredienti (nome, piatto_id) values ('Kellogs Cereal In A Cup', 152);
insert into ingredienti (nome, piatto_id) values ('Foil Wrap', 12);
insert into ingredienti (nome, piatto_id) values ('Bread - Hamburger Buns', 182);
insert into ingredienti (nome, piatto_id) values ('Cheese - Parmesan Grated', 94);
insert into ingredienti (nome, piatto_id) values ('Wine - Rhine Riesling Wolf Blass', 314);
insert into ingredienti (nome, piatto_id) values ('Bread Country Roll', 27);
insert into ingredienti (nome, piatto_id) values ('Sauce - Plum', 395);
insert into ingredienti (nome, piatto_id) values ('Puree - Mocha', 173);
insert into ingredienti (nome, piatto_id) values ('Blue Curacao - Marie Brizard', 365);
insert into ingredienti (nome, piatto_id) values ('Fond - Chocolate', 122);
insert into ingredienti (nome, piatto_id) values ('Noodles - Steamed Chow Mein', 207);
insert into ingredienti (nome, piatto_id) values ('Tomatoes', 234);
insert into ingredienti (nome, piatto_id) values ('Chinese Foods - Thick Noodles', 263);
insert into ingredienti (nome, piatto_id) values ('Soup - Verve - Chipotle Chicken', 163);
insert into ingredienti (nome, piatto_id) values ('Bread - Italian Roll With Herbs', 390);
insert into ingredienti (nome, piatto_id) values ('Pastry - Trippleberry Muffin - Mini', 149);
insert into ingredienti (nome, piatto_id) values ('Wine - Black Tower Qr', 86);
insert into ingredienti (nome, piatto_id) values ('Hipnotiq Liquor', 126);
insert into ingredienti (nome, piatto_id) values ('Rosemary - Fresh', 318);
insert into ingredienti (nome, piatto_id) values ('Paper Towel Touchless', 297);
insert into ingredienti (nome, piatto_id) values ('Beef - Sushi Flat Iron Steak', 189);
insert into ingredienti (nome, piatto_id) values ('Longos - Lasagna Beef', 109);
insert into ingredienti (nome, piatto_id) values ('Milk - 2% 250 Ml', 209);
insert into ingredienti (nome, piatto_id) values ('Scrubbie - Scotchbrite Hand Pad', 214);
insert into ingredienti (nome, piatto_id) values ('Turnip - White', 217);
insert into ingredienti (nome, piatto_id) values ('Milk - 2%', 123);
insert into ingredienti (nome, piatto_id) values ('Skirt - 29 Foot', 284);
insert into ingredienti (nome, piatto_id) values ('Fish - Halibut, Cold Smoked', 352);
insert into ingredienti (nome, piatto_id) values ('Wine - Zonnebloem Pinotage', 10);
insert into ingredienti (nome, piatto_id) values ('Nut - Hazelnut, Whole', 313);
insert into ingredienti (nome, piatto_id) values ('Kippers - Smoked', 260);
insert into ingredienti (nome, piatto_id) values ('Milk - Condensed', 77);
insert into ingredienti (nome, piatto_id) values ('Bread - Roll, Whole Wheat', 306);
insert into ingredienti (nome, piatto_id) values ('Kirsch - Schloss', 208);
insert into ingredienti (nome, piatto_id) values ('Wine - Blue Nun Qualitatswein', 115);
insert into ingredienti (nome, piatto_id) values ('Plaintain', 184);
insert into ingredienti (nome, piatto_id) values ('Crab - Meat Combo', 100);
insert into ingredienti (nome, piatto_id) values ('Lady Fingers', 83);
insert into ingredienti (nome, piatto_id) values ('Beer - Guiness', 173);
insert into ingredienti (nome, piatto_id) values ('Oyster - In Shell', 257);
insert into ingredienti (nome, piatto_id) values ('Tea - Lemon Scented', 381);
insert into ingredienti (nome, piatto_id) values ('Chicken - Whole Fryers', 271);
insert into ingredienti (nome, piatto_id) values ('Tomatoes - Orange', 311);
insert into ingredienti (nome, piatto_id) values ('Liqueur - Melon', 179);
insert into ingredienti (nome, piatto_id) values ('Chip - Potato Dill Pickle', 278);
insert into ingredienti (nome, piatto_id) values ('True - Vue Containers', 371);
insert into ingredienti (nome, piatto_id) values ('Cod - Salted, Boneless', 105);
insert into ingredienti (nome, piatto_id) values ('Juice - Clam, 46 Oz', 231);
insert into ingredienti (nome, piatto_id) values ('Food Colouring - Red', 15);
insert into ingredienti (nome, piatto_id) values ('Swiss Chard - Red', 174);
insert into ingredienti (nome, piatto_id) values ('Longos - Chicken Cordon Bleu', 162);
insert into ingredienti (nome, piatto_id) values ('Kaffir Lime Leaves', 40);
insert into ingredienti (nome, piatto_id) values ('Amaretto', 13);
insert into ingredienti (nome, piatto_id) values ('Steampan - Lid For Half Size', 395);
insert into ingredienti (nome, piatto_id) values ('Savory', 129);
insert into ingredienti (nome, piatto_id) values ('Rice Paper', 173);
insert into ingredienti (nome, piatto_id) values ('Juice - Apple, 500 Ml', 82);
insert into ingredienti (nome, piatto_id) values ('Yoghurt Tubes', 126);
insert into ingredienti (nome, piatto_id) values ('Kellogs Special K Cereal', 136);
insert into ingredienti (nome, piatto_id) values ('Pepper - Jalapeno', 240);
insert into ingredienti (nome, piatto_id) values ('Chutney Sauce - Mango', 230);
insert into ingredienti (nome, piatto_id) values ('Muffin Mix - Banana Nut', 176);
insert into ingredienti (nome, piatto_id) values ('Wine - Valpolicella Masi', 170);
insert into ingredienti (nome, piatto_id) values ('Pepper - Red Chili', 339);
insert into ingredienti (nome, piatto_id) values ('Doilies - 8, Paper', 201);
insert into ingredienti (nome, piatto_id) values ('Dates', 122);
insert into ingredienti (nome, piatto_id) values ('Sambuca - Opal Nera', 4);
insert into ingredienti (nome, piatto_id) values ('Nantucket - Orange Mango Cktl', 159);
insert into ingredienti (nome, piatto_id) values ('Bread - Rye', 213);
insert into ingredienti (nome, piatto_id) values ('Strawberries - California', 180);
insert into ingredienti (nome, piatto_id) values ('Miso Paste White', 103);
insert into ingredienti (nome, piatto_id) values ('Milk - Chocolate 500ml', 235);
insert into ingredienti (nome, piatto_id) values ('Capon - Breast, Wing On', 348);
insert into ingredienti (nome, piatto_id) values ('Coffee - Beans, Whole', 13);
insert into ingredienti (nome, piatto_id) values ('Wine - Red, Gallo, Merlot', 173);
insert into ingredienti (nome, piatto_id) values ('Pail For Lid 1537', 130);
insert into ingredienti (nome, piatto_id) values ('Cape Capensis - Fillet', 227);
insert into ingredienti (nome, piatto_id) values ('Strawberries - California', 355);
insert into ingredienti (nome, piatto_id) values ('Cheese - Roquefort Pappillon', 298);
insert into ingredienti (nome, piatto_id) values ('Gatorade - Lemon Lime', 208);
insert into ingredienti (nome, piatto_id) values ('Puree - Kiwi', 278);
insert into ingredienti (nome, piatto_id) values ('Wine - Harrow Estates, Vidal', 368);
insert into ingredienti (nome, piatto_id) values ('Bread - Crumbs, Bulk', 128);
insert into ingredienti (nome, piatto_id) values ('Wine - Masi Valpolocell', 174);
insert into ingredienti (nome, piatto_id) values ('Saskatoon Berries - Frozen', 127);
insert into ingredienti (nome, piatto_id) values ('Chilli Paste, Hot Sambal Oelek', 118);
insert into ingredienti (nome, piatto_id) values ('Pork Loin Bine - In Frenched', 116);
insert into ingredienti (nome, piatto_id) values ('Ecolab - Power Fusion', 150);
insert into ingredienti (nome, piatto_id) values ('Container - Hngd Cll Blk 7x7x3', 310);
insert into ingredienti (nome, piatto_id) values ('Bread - White, Sliced', 149);
insert into ingredienti (nome, piatto_id) values ('Tart Shells - Sweet, 2', 96);
insert into ingredienti (nome, piatto_id) values ('Scallops 60/80 Iqf', 293);
insert into ingredienti (nome, piatto_id) values ('Peas - Pigeon, Dry', 359);
insert into ingredienti (nome, piatto_id) values ('Flour - Fast / Rapid', 290);
insert into ingredienti (nome, piatto_id) values ('Bread - Malt', 22);
insert into ingredienti (nome, piatto_id) values ('Glucose', 13);
insert into ingredienti (nome, piatto_id) values ('English Muffin', 102);
insert into ingredienti (nome, piatto_id) values ('Soup - Base Broth Beef', 382);
insert into ingredienti (nome, piatto_id) values ('Toamtoes 6x7 Select', 56);
insert into ingredienti (nome, piatto_id) values ('Chef Hat 25cm', 11);
insert into ingredienti (nome, piatto_id) values ('Cranberry Foccacia', 295);
insert into ingredienti (nome, piatto_id) values ('Melon - Watermelon Yellow', 58);
insert into ingredienti (nome, piatto_id) values ('Orange - Blood', 360);
insert into ingredienti (nome, piatto_id) values ('Vanilla Beans', 151);
insert into ingredienti (nome, piatto_id) values ('Bay Leaf', 113);
insert into ingredienti (nome, piatto_id) values ('Lobster - Base', 333);
insert into ingredienti (nome, piatto_id) values ('Flax Seed', 293);
insert into ingredienti (nome, piatto_id) values ('Beans - Turtle, Black, Dry', 30);
insert into ingredienti (nome, piatto_id) values ('Glaze - Clear', 328);
insert into ingredienti (nome, piatto_id) values ('Wine - Baron De Rothschild', 325);
insert into ingredienti (nome, piatto_id) values ('Split Peas - Yellow, Dry', 261);
insert into ingredienti (nome, piatto_id) values ('Cinnamon - Stick', 149);
insert into ingredienti (nome, piatto_id) values ('Bread - Multigrain Oval', 71);
insert into ingredienti (nome, piatto_id) values ('Duck - Legs', 260);
insert into ingredienti (nome, piatto_id) values ('Wine - Casillero Del Diablo', 79);
insert into ingredienti (nome, piatto_id) values ('Kiwi', 10);
insert into ingredienti (nome, piatto_id) values ('Pepper - Orange', 378);
insert into ingredienti (nome, piatto_id) values ('Knife Plastic - White', 209);
insert into ingredienti (nome, piatto_id) values ('Potatoes - Parissienne', 357);
insert into ingredienti (nome, piatto_id) values ('Sea Urchin', 56);
insert into ingredienti (nome, piatto_id) values ('Vacuum Bags 12x16', 279);
insert into ingredienti (nome, piatto_id) values ('Beef - Cooked, Corned', 349);
insert into ingredienti (nome, piatto_id) values ('Danishes - Mini Raspberry', 11);
insert into ingredienti (nome, piatto_id) values ('Soup - Campbells Bean Medley', 233);
insert into ingredienti (nome, piatto_id) values ('Flour Dark Rye', 249);
insert into ingredienti (nome, piatto_id) values ('V8 Splash Strawberry Kiwi', 254);
insert into ingredienti (nome, piatto_id) values ('Nori Sea Weed', 297);
insert into ingredienti (nome, piatto_id) values ('Horseradish - Prepared', 54);
insert into ingredienti (nome, piatto_id) values ('Stock - Veal, White', 313);
insert into ingredienti (nome, piatto_id) values ('Pickles - Gherkins', 294);
insert into ingredienti (nome, piatto_id) values ('Pears - Bosc', 273);
insert into ingredienti (nome, piatto_id) values ('Bread - Multigrain, Loaf', 74);
insert into ingredienti (nome, piatto_id) values ('Beef - Bones, Marrow', 325);
insert into ingredienti (nome, piatto_id) values ('Milk - Chocolate 250 Ml', 99);
insert into ingredienti (nome, piatto_id) values ('Lettuce - Frisee', 328);
insert into ingredienti (nome, piatto_id) values ('Initation Crab Meat', 33);
insert into ingredienti (nome, piatto_id) values ('Milk - Condensed', 173);
insert into ingredienti (nome, piatto_id) values ('Flour - Whole Wheat', 51);
insert into ingredienti (nome, piatto_id) values ('Wine - Gewurztraminer Pierre', 333);
insert into ingredienti (nome, piatto_id) values ('Carrots - Purple, Organic', 308);
insert into ingredienti (nome, piatto_id) values ('Soap - Mr.clean Floor Soap', 392);
insert into ingredienti (nome, piatto_id) values ('Beef - Baby, Liver', 120);
insert into ingredienti (nome, piatto_id) values ('Radish - Black, Winter, Organic', 395);
insert into ingredienti (nome, piatto_id) values ('Rice Paper', 391);
insert into ingredienti (nome, piatto_id) values ('Wine - Prem Select Charddonany', 376);
insert into ingredienti (nome, piatto_id) values ('Syrup - Monin - Granny Smith', 234);
insert into ingredienti (nome, piatto_id) values ('Corn Meal', 230);
insert into ingredienti (nome, piatto_id) values ('Ranchero - Primerba, Paste', 227);
insert into ingredienti (nome, piatto_id) values ('Tuna - Salad Premix', 112);
insert into ingredienti (nome, piatto_id) values ('Oil - Truffle, Black', 84);
insert into ingredienti (nome, piatto_id) values ('Bagel - 12 Grain Preslice', 314);
insert into ingredienti (nome, piatto_id) values ('Cookies Almond Hazelnut', 2);
insert into ingredienti (nome, piatto_id) values ('Salmon - Fillets', 344);
insert into ingredienti (nome, piatto_id) values ('Water - Spring Water, 355 Ml', 45);
insert into ingredienti (nome, piatto_id) values ('Jam - Strawberry, 20 Ml Jar', 24);
insert into ingredienti (nome, piatto_id) values ('Cherries - Maraschino,jar', 174);
insert into ingredienti (nome, piatto_id) values ('Cleaner - Bleach', 95);
insert into ingredienti (nome, piatto_id) values ('Bread - Crusty Italian Poly', 138);
insert into ingredienti (nome, piatto_id) values ('Fennel', 143);
insert into ingredienti (nome, piatto_id) values ('Apple - Northern Spy', 333);
insert into ingredienti (nome, piatto_id) values ('Wine - Manischewitz Concord', 279);
insert into ingredienti (nome, piatto_id) values ('Energy Drink - Franks Pineapple', 22);
insert into ingredienti (nome, piatto_id) values ('Shrimp, Dried, Small / Lb', 320);
insert into ingredienti (nome, piatto_id) values ('Sauce - Apple, Unsweetened', 341);
insert into ingredienti (nome, piatto_id) values ('Cocoa Feuilletine', 257);
insert into ingredienti (nome, piatto_id) values ('Allspice - Jamaican', 186);
insert into ingredienti (nome, piatto_id) values ('Wheat - Soft Kernal Of Wheat', 380);
insert into ingredienti (nome, piatto_id) values ('Melon - Honey Dew', 219);
insert into ingredienti (nome, piatto_id) values ('Dome Lid Clear P92008h', 15);
insert into ingredienti (nome, piatto_id) values ('Salmon - Atlantic, Fresh, Whole', 274);
insert into ingredienti (nome, piatto_id) values ('Nantucket - Pomegranate Pear', 387);
insert into ingredienti (nome, piatto_id) values ('Chicken Breast Halal', 115);
insert into ingredienti (nome, piatto_id) values ('Wine - German Riesling', 81);
insert into ingredienti (nome, piatto_id) values ('Truffle Cups - White Paper', 119);
insert into ingredienti (nome, piatto_id) values ('Flour Pastry Super Fine', 122);
insert into ingredienti (nome, piatto_id) values ('Sesame Seed Black', 332);
insert into ingredienti (nome, piatto_id) values ('Jameson Irish Whiskey', 36);
insert into ingredienti (nome, piatto_id) values ('Milk - 1%', 104);
insert into ingredienti (nome, piatto_id) values ('Caviar - Salmon', 64);
insert into ingredienti (nome, piatto_id) values ('Flour - Fast / Rapid', 37);
insert into ingredienti (nome, piatto_id) values ('Cheese - Provolone', 295);
insert into ingredienti (nome, piatto_id) values ('Pie Shell - 5', 77);
insert into ingredienti (nome, piatto_id) values ('Milk - 2% 250 Ml', 195);
insert into ingredienti (nome, piatto_id) values ('Muffin Mix - Corn Harvest', 13);
insert into ingredienti (nome, piatto_id) values ('Turkey - Breast, Boneless Sk On', 52);
insert into ingredienti (nome, piatto_id) values ('Pork - Ham Hocks - Smoked', 375);
insert into ingredienti (nome, piatto_id) values ('Oil - Peanut', 155);
insert into ingredienti (nome, piatto_id) values ('Garam Masala Powder', 218);
insert into ingredienti (nome, piatto_id) values ('Bacon Strip Precooked', 231);
insert into ingredienti (nome, piatto_id) values ('Mushroom - Portebello', 379);
insert into ingredienti (nome, piatto_id) values ('Muffin - Banana Nut Individual', 394);
insert into ingredienti (nome, piatto_id) values ('Juice - Orange', 256);
insert into ingredienti (nome, piatto_id) values ('Gatorade - Orange', 169);
insert into ingredienti (nome, piatto_id) values ('Spinach - Baby', 60);
insert into ingredienti (nome, piatto_id) values ('Macaroons - Homestyle Two Bit', 95);
insert into ingredienti (nome, piatto_id) values ('Ecolab Crystal Fusion', 143);
insert into ingredienti (nome, piatto_id) values ('Bacon Strip Precooked', 338);
insert into ingredienti (nome, piatto_id) values ('Oil - Sunflower', 159);
insert into ingredienti (nome, piatto_id) values ('Sausage - Chorizo', 286);
insert into ingredienti (nome, piatto_id) values ('Nantucket Orange Juice', 81);
insert into ingredienti (nome, piatto_id) values ('Nantucket Apple Juice', 15);
insert into ingredienti (nome, piatto_id) values ('Jolt Cola', 332);
insert into ingredienti (nome, piatto_id) values ('Cheese - Colby', 152);
insert into ingredienti (nome, piatto_id) values ('Longos - Chicken Curried', 348);
insert into ingredienti (nome, piatto_id) values ('Wine - Fontanafredda Barolo', 100);
insert into ingredienti (nome, piatto_id) values ('Tumeric', 338);
insert into ingredienti (nome, piatto_id) values ('Nantucket Apple Juice', 345);
insert into ingredienti (nome, piatto_id) values ('Cheese - Marble', 164);
insert into ingredienti (nome, piatto_id) values ('Thermometer Digital', 242);
insert into ingredienti (nome, piatto_id) values ('Sugar - Invert', 152);
insert into ingredienti (nome, piatto_id) values ('Duck - Fat', 180);
insert into ingredienti (nome, piatto_id) values ('Truffle Shells - White Chocolate', 379);
insert into ingredienti (nome, piatto_id) values ('Waffle Stix', 273);
insert into ingredienti (nome, piatto_id) values ('Ham - Procutinni', 187);
insert into ingredienti (nome, piatto_id) values ('Muffin Mix - Carrot', 196);
insert into ingredienti (nome, piatto_id) values ('Arctic Char - Fresh, Whole', 265);
insert into ingredienti (nome, piatto_id) values ('Muffin Carrot - Individual', 181);
insert into ingredienti (nome, piatto_id) values ('Lamb Rack - Ontario', 105);
insert into ingredienti (nome, piatto_id) values ('Plastic Wrap', 124);
insert into ingredienti (nome, piatto_id) values ('Truffle Cups - Brown', 176);
insert into ingredienti (nome, piatto_id) values ('Wine - Ej Gallo Sierra Valley', 21);
insert into ingredienti (nome, piatto_id) values ('Anchovy Fillets', 107);
insert into ingredienti (nome, piatto_id) values ('Green Scrubbie Pad H.duty', 251);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Concha Y Toro', 363);
insert into ingredienti (nome, piatto_id) values ('Nestea - Ice Tea, Diet', 179);
insert into ingredienti (nome, piatto_id) values ('Campari', 82);
insert into ingredienti (nome, piatto_id) values ('Nantuket Peach Orange', 372);
insert into ingredienti (nome, piatto_id) values ('Pasta - Cannelloni, Sheets, Fresh', 353);
insert into ingredienti (nome, piatto_id) values ('Bok Choy - Baby', 106);
insert into ingredienti (nome, piatto_id) values ('Sobe - Berry Energy', 63);
insert into ingredienti (nome, piatto_id) values ('Wine - Rosso Toscano Igt', 317);
insert into ingredienti (nome, piatto_id) values ('Extract - Almond', 22);
insert into ingredienti (nome, piatto_id) values ('Oil - Shortening - All - Purpose', 317);
insert into ingredienti (nome, piatto_id) values ('Dill Weed - Dry', 19);
insert into ingredienti (nome, piatto_id) values ('Bag Clear 10 Lb', 112);
insert into ingredienti (nome, piatto_id) values ('Squash - Pattypan, Yellow', 231);
insert into ingredienti (nome, piatto_id) values ('Veal - Brisket, Provimi, Bone - In', 28);
insert into ingredienti (nome, piatto_id) values ('Beans - Black Bean, Canned', 198);
insert into ingredienti (nome, piatto_id) values ('Tart - Raisin And Pecan', 329);
insert into ingredienti (nome, piatto_id) values ('Syrup - Golden, Lyles', 26);
insert into ingredienti (nome, piatto_id) values ('Brandy - Bar', 49);
insert into ingredienti (nome, piatto_id) values ('Wine - Masi Valpolocell', 156);
insert into ingredienti (nome, piatto_id) values ('Cheese - Woolwich Goat, Log', 233);
insert into ingredienti (nome, piatto_id) values ('Steampan Lid', 5);
insert into ingredienti (nome, piatto_id) values ('Cake - Pancake', 75);
insert into ingredienti (nome, piatto_id) values ('Longos - Grilled Chicken With', 393);
insert into ingredienti (nome, piatto_id) values ('Galliano', 205);
insert into ingredienti (nome, piatto_id) values ('Appetizer - Lobster Phyllo Roll', 131);
insert into ingredienti (nome, piatto_id) values ('Lamb Rack - Ontario', 220);
insert into ingredienti (nome, piatto_id) values ('Wine - Sawmill Creek Autumn', 106);
insert into ingredienti (nome, piatto_id) values ('Olives - Stuffed', 394);
insert into ingredienti (nome, piatto_id) values ('Nut - Pine Nuts, Whole', 357);
insert into ingredienti (nome, piatto_id) values ('Wine - Chablis 2003 Champs', 53);
insert into ingredienti (nome, piatto_id) values ('Food Colouring - Orange', 285);
insert into ingredienti (nome, piatto_id) values ('Salt - Sea', 81);
insert into ingredienti (nome, piatto_id) values ('Cheese - Gouda', 176);
insert into ingredienti (nome, piatto_id) values ('Shopper Bag - S - 4', 242);
insert into ingredienti (nome, piatto_id) values ('Bread - Dark Rye', 276);
insert into ingredienti (nome, piatto_id) values ('Sugar Thermometer', 125);
insert into ingredienti (nome, piatto_id) values ('Sobe - Liz Blizz', 103);
insert into ingredienti (nome, piatto_id) values ('Oil - Margarine', 227);
insert into ingredienti (nome, piatto_id) values ('Potatoes - Yukon Gold, 80 Ct', 20);
insert into ingredienti (nome, piatto_id) values ('Ham - Procutinni', 74);
insert into ingredienti (nome, piatto_id) values ('Mustard - Pommery', 350);
insert into ingredienti (nome, piatto_id) values ('Star Fruit', 320);
insert into ingredienti (nome, piatto_id) values ('Beef - Chuck, Boneless', 127);
insert into ingredienti (nome, piatto_id) values ('Paste - Black Olive', 117);
insert into ingredienti (nome, piatto_id) values ('Potatoes - Yukon Gold 5 Oz', 182);
insert into ingredienti (nome, piatto_id) values ('Cake - Dulce De Leche', 269);
insert into ingredienti (nome, piatto_id) values ('Crab - Blue, Frozen', 78);
insert into ingredienti (nome, piatto_id) values ('Carbonated Water - White Grape', 247);
insert into ingredienti (nome, piatto_id) values ('Beef - Ox Tongue', 285);
insert into ingredienti (nome, piatto_id) values ('Bols Melon Liqueur', 300);
insert into ingredienti (nome, piatto_id) values ('Pepper - Jalapeno', 40);
insert into ingredienti (nome, piatto_id) values ('French Kiss Vanilla', 309);
insert into ingredienti (nome, piatto_id) values ('Mackerel Whole Fresh', 62);
insert into ingredienti (nome, piatto_id) values ('Cookies Oatmeal Raisin', 142);
insert into ingredienti (nome, piatto_id) values ('Heavy Duty Dust Pan', 245);
insert into ingredienti (nome, piatto_id) values ('Radish', 169);
insert into ingredienti (nome, piatto_id) values ('Persimmons', 236);
insert into ingredienti (nome, piatto_id) values ('Buffalo - Tenderloin', 166);
insert into ingredienti (nome, piatto_id) values ('Pepper - Chili Powder', 2);
insert into ingredienti (nome, piatto_id) values ('Pastry - Chocolate Chip Muffin', 162);
insert into ingredienti (nome, piatto_id) values ('Appetizer - Assorted Box', 158);
insert into ingredienti (nome, piatto_id) values ('Juice - V8 Splash', 82);
insert into ingredienti (nome, piatto_id) values ('Chicken - Base, Ultimate', 15);
insert into ingredienti (nome, piatto_id) values ('Flavouring - Orange', 51);
insert into ingredienti (nome, piatto_id) values ('Water - Mineral, Natural', 171);
insert into ingredienti (nome, piatto_id) values ('Sobe - Berry Energy', 257);
insert into ingredienti (nome, piatto_id) values ('Remy Red', 53);
insert into ingredienti (nome, piatto_id) values ('Cookie Choc', 346);
insert into ingredienti (nome, piatto_id) values ('Peas - Frozen', 220);
insert into ingredienti (nome, piatto_id) values ('Soup - Canadian Pea, Dry Mix', 108);
insert into ingredienti (nome, piatto_id) values ('Beer - Sleemans Honey Brown', 285);
insert into ingredienti (nome, piatto_id) values ('Mushroom - Chanterelle, Dry', 118);
insert into ingredienti (nome, piatto_id) values ('Spinach - Spinach Leaf', 324);
insert into ingredienti (nome, piatto_id) values ('Coconut Milk - Unsweetened', 30);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Lindemans Bin 95', 317);
insert into ingredienti (nome, piatto_id) values ('Olives - Black, Pitted', 113);
insert into ingredienti (nome, piatto_id) values ('Pasta - Fusili Tri - Coloured', 36);
insert into ingredienti (nome, piatto_id) values ('Pasta - Ravioli', 261);
insert into ingredienti (nome, piatto_id) values ('Truffle Cups Green', 68);
insert into ingredienti (nome, piatto_id) values ('Dill Weed - Fresh', 262);
insert into ingredienti (nome, piatto_id) values ('Appetizer - Sausage Rolls', 260);
insert into ingredienti (nome, piatto_id) values ('Longos - Chicken Curried', 103);
insert into ingredienti (nome, piatto_id) values ('Juice - Prune', 377);
insert into ingredienti (nome, piatto_id) values ('Crab Meat Claw Pasteurise', 360);
insert into ingredienti (nome, piatto_id) values ('Jameson Irish Whiskey', 324);
insert into ingredienti (nome, piatto_id) values ('Cheese - Cheddar, Old White', 357);
insert into ingredienti (nome, piatto_id) values ('Pepsi - 600ml', 175);
insert into ingredienti (nome, piatto_id) values ('Coriander - Seed', 66);
insert into ingredienti (nome, piatto_id) values ('Soup - Base Broth Chix', 88);
insert into ingredienti (nome, piatto_id) values ('Vermouth - Sweet, Cinzano', 287);
insert into ingredienti (nome, piatto_id) values ('Shallots', 37);
insert into ingredienti (nome, piatto_id) values ('Eggplant - Asian', 235);
insert into ingredienti (nome, piatto_id) values ('Wine - Trimbach Pinot Blanc', 92);
insert into ingredienti (nome, piatto_id) values ('Potatoes - Pei 10 Oz', 150);
insert into ingredienti (nome, piatto_id) values ('Soup - Campbells Broccoli', 78);
insert into ingredienti (nome, piatto_id) values ('Soup - French Onion, Dry', 190);
insert into ingredienti (nome, piatto_id) values ('Wine - Vineland Estate Semi - Dry', 56);
insert into ingredienti (nome, piatto_id) values ('Beef - Diced', 238);
insert into ingredienti (nome, piatto_id) values ('Gloves - Goldtouch Disposable', 186);
insert into ingredienti (nome, piatto_id) values ('Pepsi, 355 Ml', 167);
insert into ingredienti (nome, piatto_id) values ('Cumin - Whole', 108);
insert into ingredienti (nome, piatto_id) values ('Flour - Corn, Fine', 99);
insert into ingredienti (nome, piatto_id) values ('Soup Campbells Turkey Veg.', 363);
insert into ingredienti (nome, piatto_id) values ('Veal - Leg', 350);
insert into ingredienti (nome, piatto_id) values ('Sansho Powder', 158);
insert into ingredienti (nome, piatto_id) values ('Squeeze Bottle', 11);
insert into ingredienti (nome, piatto_id) values ('Beef - Bones, Cut - Up', 360);
insert into ingredienti (nome, piatto_id) values ('Plasticspoonblack', 335);
insert into ingredienti (nome, piatto_id) values ('Swordfish Loin Portions', 316);
insert into ingredienti (nome, piatto_id) values ('Dried Cranberries', 13);
insert into ingredienti (nome, piatto_id) values ('Russian Prince', 192);
insert into ingredienti (nome, piatto_id) values ('Mussels - Frozen', 354);
insert into ingredienti (nome, piatto_id) values ('Ecolab - Hobart Washarm End Cap', 17);
insert into ingredienti (nome, piatto_id) values ('Versatainer Nc - 888', 298);
insert into ingredienti (nome, piatto_id) values ('Coffee - Flavoured', 64);
insert into ingredienti (nome, piatto_id) values ('Yams', 322);
insert into ingredienti (nome, piatto_id) values ('Muffin Mix - Carrot', 244);
insert into ingredienti (nome, piatto_id) values ('Pasta - Fusili Tri - Coloured', 275);
insert into ingredienti (nome, piatto_id) values ('Cheese - Valancey', 343);
insert into ingredienti (nome, piatto_id) values ('Scallops - 10/20', 181);
insert into ingredienti (nome, piatto_id) values ('Pastry - Banana Muffin - Mini', 246);
insert into ingredienti (nome, piatto_id) values ('Muffin Batt - Carrot Spice', 351);
insert into ingredienti (nome, piatto_id) values ('Oxtail - Cut', 12);
insert into ingredienti (nome, piatto_id) values ('Tendrils - Baby Pea, Organic', 275);
insert into ingredienti (nome, piatto_id) values ('Wine - Cotes Du Rhone Parallele', 315);
insert into ingredienti (nome, piatto_id) values ('Juice - Clamato, 341 Ml', 375);
insert into ingredienti (nome, piatto_id) values ('Kellogs Cereal In A Cup', 255);
insert into ingredienti (nome, piatto_id) values ('V8 - Tropical Blend', 121);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Colubia Cresh', 155);
insert into ingredienti (nome, piatto_id) values ('Orange - Canned, Mandarin', 58);
insert into ingredienti (nome, piatto_id) values ('Scallops - 20/30', 364);
insert into ingredienti (nome, piatto_id) values ('Bread - Ciabatta Buns', 329);
insert into ingredienti (nome, piatto_id) values ('Wine - Port Late Bottled Vintage', 314);
insert into ingredienti (nome, piatto_id) values ('Laundry - Bag Cloth', 31);
insert into ingredienti (nome, piatto_id) values ('Pasta - Elbows, Macaroni, Dry', 287);
insert into ingredienti (nome, piatto_id) values ('Turnip - Wax', 220);
insert into ingredienti (nome, piatto_id) values ('Higashimaru Usukuchi Soy', 350);
insert into ingredienti (nome, piatto_id) values ('Flour - Strong Pizza', 137);
insert into ingredienti (nome, piatto_id) values ('Sour Cream', 352);
insert into ingredienti (nome, piatto_id) values ('Pastry - Apple Muffins - Mini', 13);
insert into ingredienti (nome, piatto_id) values ('Curry Powder', 290);
insert into ingredienti (nome, piatto_id) values ('Beer - Creemore', 358);
insert into ingredienti (nome, piatto_id) values ('Pork - Ground', 270);
insert into ingredienti (nome, piatto_id) values ('Cherries - Maraschino,jar', 325);
insert into ingredienti (nome, piatto_id) values ('Contreau', 307);
insert into ingredienti (nome, piatto_id) values ('Syrup - Monin - Passion Fruit', 282);
insert into ingredienti (nome, piatto_id) values ('Squash - Butternut', 244);
insert into ingredienti (nome, piatto_id) values ('Flavouring Vanilla Artificial', 236);
insert into ingredienti (nome, piatto_id) values ('Pails With Lids', 165);
insert into ingredienti (nome, piatto_id) values ('The Pop Shoppe Pinapple', 341);
insert into ingredienti (nome, piatto_id) values ('Tea - Vanilla Chai', 312);
insert into ingredienti (nome, piatto_id) values ('Scallops - 10/20', 275);
insert into ingredienti (nome, piatto_id) values ('Propel Sport Drink', 152);
insert into ingredienti (nome, piatto_id) values ('Tequila Rose Cream Liquor', 305);
insert into ingredienti (nome, piatto_id) values ('Lambcasing', 267);
insert into ingredienti (nome, piatto_id) values ('Bread - Focaccia Quarter', 46);
insert into ingredienti (nome, piatto_id) values ('Raisin - Golden', 221);
insert into ingredienti (nome, piatto_id) values ('Sauce - Marinara', 372);
insert into ingredienti (nome, piatto_id) values ('Pastrami', 53);
insert into ingredienti (nome, piatto_id) values ('Potatoes - Yukon Gold, 80 Ct', 112);
insert into ingredienti (nome, piatto_id) values ('Irish Cream - Butterscotch', 270);
insert into ingredienti (nome, piatto_id) values ('Kiwano', 144);
insert into ingredienti (nome, piatto_id) values ('Bagel - Whole White Sesame', 236);
insert into ingredienti (nome, piatto_id) values ('Bar Mix - Lemon', 12);
insert into ingredienti (nome, piatto_id) values ('Cheese - Le Cru Du Clocher', 347);
insert into ingredienti (nome, piatto_id) values ('Squash - Acorn', 202);
insert into ingredienti (nome, piatto_id) values ('Eggplant Italian', 394);
insert into ingredienti (nome, piatto_id) values ('Milkettes - 2%', 391);
insert into ingredienti (nome, piatto_id) values ('Wine - Bourgogne 2002, La', 356);
insert into ingredienti (nome, piatto_id) values ('Lychee - Canned', 40);
insert into ingredienti (nome, piatto_id) values ('Beef Tenderloin Aaa', 296);
insert into ingredienti (nome, piatto_id) values ('Wine - Chianti Classico Riserva', 394);
insert into ingredienti (nome, piatto_id) values ('Onions - Spanish', 115);
insert into ingredienti (nome, piatto_id) values ('Fork - Plastic', 149);
insert into ingredienti (nome, piatto_id) values ('Creme De Cacao White', 93);
insert into ingredienti (nome, piatto_id) values ('Beef - Montreal Smoked Brisket', 352);
insert into ingredienti (nome, piatto_id) values ('Crab - Blue, Frozen', 72);
insert into ingredienti (nome, piatto_id) values ('Mussels - Cultivated', 94);
insert into ingredienti (nome, piatto_id) values ('Tomatoes - Grape', 59);
insert into ingredienti (nome, piatto_id) values ('Spice - Greek 1 Step', 357);
insert into ingredienti (nome, piatto_id) values ('Energy Drink - Franks Pineapple', 175);
insert into ingredienti (nome, piatto_id) values ('Cactus Pads', 2);
insert into ingredienti (nome, piatto_id) values ('V8 - Berry Blend', 202);
insert into ingredienti (nome, piatto_id) values ('Coffee - Frthy Coffee Crisp', 325);
insert into ingredienti (nome, piatto_id) values ('Turkey - Oven Roast Breast', 110);
insert into ingredienti (nome, piatto_id) values ('Cheese - Asiago', 131);
insert into ingredienti (nome, piatto_id) values ('Bread Base - Goodhearth', 321);
insert into ingredienti (nome, piatto_id) values ('Flour - Chickpea', 34);
insert into ingredienti (nome, piatto_id) values ('Bread - Frozen Basket Variety', 73);
insert into ingredienti (nome, piatto_id) values ('Sage Ground Wiberg', 150);
insert into ingredienti (nome, piatto_id) values ('Eel Fresh', 109);
insert into ingredienti (nome, piatto_id) values ('Kiwi', 154);
insert into ingredienti (nome, piatto_id) values ('Pepper - Green Thai', 220);
insert into ingredienti (nome, piatto_id) values ('Mustard - Seed', 180);
insert into ingredienti (nome, piatto_id) values ('Sauce - Hollandaise', 175);
insert into ingredienti (nome, piatto_id) values ('Bar Mix - Lime', 53);
insert into ingredienti (nome, piatto_id) values ('Coffee - Hazelnut Cream', 115);
insert into ingredienti (nome, piatto_id) values ('Soup - Knorr, Classic Can. Chili', 61);
insert into ingredienti (nome, piatto_id) values ('Ostrich - Prime Cut', 258);
insert into ingredienti (nome, piatto_id) values ('Alize Gold Passion', 20);
insert into ingredienti (nome, piatto_id) values ('Snapple - Mango Maddness', 253);
insert into ingredienti (nome, piatto_id) values ('Wine - Shiraz Wolf Blass Premium', 243);
insert into ingredienti (nome, piatto_id) values ('Beef - Rib Roast, Cap On', 128);
insert into ingredienti (nome, piatto_id) values ('Beer - Sleeman Fine Porter', 305);
insert into ingredienti (nome, piatto_id) values ('Nestea - Ice Tea, Diet', 38);
insert into ingredienti (nome, piatto_id) values ('Sherry - Dry', 154);
insert into ingredienti (nome, piatto_id) values ('Compound - Passion Fruit', 246);
insert into ingredienti (nome, piatto_id) values ('Soup - Knorr, Chicken Gumbo', 350);
insert into ingredienti (nome, piatto_id) values ('Mushroom Morel Fresh', 291);
insert into ingredienti (nome, piatto_id) values ('Puree - Kiwi', 125);
insert into ingredienti (nome, piatto_id) values ('Wine - Alsace Gewurztraminer', 271);
insert into ingredienti (nome, piatto_id) values ('Calypso - Strawberry Lemonade', 391);
insert into ingredienti (nome, piatto_id) values ('Milk - Buttermilk', 52);
insert into ingredienti (nome, piatto_id) values ('Pork - Ground', 18);
insert into ingredienti (nome, piatto_id) values ('Squash - Pepper', 228);
insert into ingredienti (nome, piatto_id) values ('Cinnamon - Stick', 398);
insert into ingredienti (nome, piatto_id) values ('Extract - Raspberry', 43);
insert into ingredienti (nome, piatto_id) values ('Wine - Harrow Estates, Vidal', 330);
insert into ingredienti (nome, piatto_id) values ('Sprouts - China Rose', 146);
insert into ingredienti (nome, piatto_id) values ('Rum - Cream, Amarula', 325);
insert into ingredienti (nome, piatto_id) values ('Rum - Dark, Bacardi, Black', 38);
insert into ingredienti (nome, piatto_id) values ('Loquat', 396);
insert into ingredienti (nome, piatto_id) values ('Crab - Soft Shell', 9);
insert into ingredienti (nome, piatto_id) values ('Canadian Emmenthal', 38);
insert into ingredienti (nome, piatto_id) values ('Island Oasis - Lemonade', 28);
insert into ingredienti (nome, piatto_id) values ('Truffle Paste', 307);
insert into ingredienti (nome, piatto_id) values ('Pepper - Pablano', 166);
insert into ingredienti (nome, piatto_id) values ('Lettuce - Belgian Endive', 310);
insert into ingredienti (nome, piatto_id) values ('Glass - Wine, Plastic, Clear 5 Oz', 343);
insert into ingredienti (nome, piatto_id) values ('Wine - Semi Dry Riesling Vineland', 76);
insert into ingredienti (nome, piatto_id) values ('Pork - Smoked Kassler', 184);
insert into ingredienti (nome, piatto_id) values ('Kaffir Lime Leaves', 73);
insert into ingredienti (nome, piatto_id) values ('Gherkin', 24);
insert into ingredienti (nome, piatto_id) values ('Vaccum Bag - 14x20', 120);
insert into ingredienti (nome, piatto_id) values ('Mountain Dew', 270);
insert into ingredienti (nome, piatto_id) values ('Crab - Meat Combo', 386);
insert into ingredienti (nome, piatto_id) values ('The Pop Shoppe - Lime Rickey', 140);
insert into ingredienti (nome, piatto_id) values ('Mustard - Pommery', 173);
insert into ingredienti (nome, piatto_id) values ('Table Cloth 91x91 Colour', 110);
insert into ingredienti (nome, piatto_id) values ('Nacho Chips', 21);
insert into ingredienti (nome, piatto_id) values ('Yeast Dry - Fermipan', 378);
insert into ingredienti (nome, piatto_id) values ('Tart Shells - Savory, 4', 399);
insert into ingredienti (nome, piatto_id) values ('Pork - Shoulder', 1);
insert into ingredienti (nome, piatto_id) values ('Beef Cheek Fresh', 105);
insert into ingredienti (nome, piatto_id) values ('Eggplant - Regular', 218);
insert into ingredienti (nome, piatto_id) values ('Sparkling Wine - Rose, Freixenet', 77);
insert into ingredienti (nome, piatto_id) values ('Sobe - Berry Energy', 376);
insert into ingredienti (nome, piatto_id) values ('Cheese - Cottage Cheese', 51);
insert into ingredienti (nome, piatto_id) values ('Placemat - Scallop, White', 351);
insert into ingredienti (nome, piatto_id) values ('Wine - Red, Concha Y Toro', 360);
insert into ingredienti (nome, piatto_id) values ('Petit Baguette', 326);
insert into ingredienti (nome, piatto_id) values ('Cookies - Fortune', 36);
insert into ingredienti (nome, piatto_id) values ('Octopus - Baby, Cleaned', 103);
insert into ingredienti (nome, piatto_id) values ('Pumpkin', 45);
insert into ingredienti (nome, piatto_id) values ('Cheese - Cream Cheese', 132);
insert into ingredienti (nome, piatto_id) values ('Cookies - Englishbay Chochip', 181);
insert into ingredienti (nome, piatto_id) values ('Long Island Ice Tea', 120);
insert into ingredienti (nome, piatto_id) values ('Coffee - 10oz Cup 92961', 175);
insert into ingredienti (nome, piatto_id) values ('Alize Gold Passion', 224);
insert into ingredienti (nome, piatto_id) values ('Wine - Red, Cooking', 400);
insert into ingredienti (nome, piatto_id) values ('Vaccum Bag - 14x20', 52);
insert into ingredienti (nome, piatto_id) values ('Paper Cocktail Umberlla 80 - 180', 140);
insert into ingredienti (nome, piatto_id) values ('Coffee - Almond Amaretto', 10);
insert into ingredienti (nome, piatto_id) values ('Kirsch - Schloss', 373);
insert into ingredienti (nome, piatto_id) values ('Rum - Cream, Amarula', 252);
insert into ingredienti (nome, piatto_id) values ('The Pop Shoppe - Root Beer', 382);
insert into ingredienti (nome, piatto_id) values ('Chips Potato Reg 43g', 344);
insert into ingredienti (nome, piatto_id) values ('Vinegar - Cider', 21);
insert into ingredienti (nome, piatto_id) values ('Ice Cream Bar - Rolo Cone', 263);
insert into ingredienti (nome, piatto_id) values ('Dc - Sakura Fu', 284);
insert into ingredienti (nome, piatto_id) values ('Pate - Peppercorn', 369);
insert into ingredienti (nome, piatto_id) values ('Longos - Penne With Pesto', 399);
insert into ingredienti (nome, piatto_id) values ('Sauce - Plum', 296);
insert into ingredienti (nome, piatto_id) values ('Doilies - 7, Paper', 212);
insert into ingredienti (nome, piatto_id) values ('Chips - Assorted', 322);
insert into ingredienti (nome, piatto_id) values ('Onions - Dried, Chopped', 317);
insert into ingredienti (nome, piatto_id) values ('Pie Filling - Apple', 344);
insert into ingredienti (nome, piatto_id) values ('Mustard - Individual Pkg', 320);
insert into ingredienti (nome, piatto_id) values ('Yogurt - Strawberry, 175 Gr', 379);
insert into ingredienti (nome, piatto_id) values ('Ostrich - Fan Fillet', 381);
insert into ingredienti (nome, piatto_id) values ('Lobster - Canned Premium', 373);
insert into ingredienti (nome, piatto_id) values ('Stock - Beef, Brown', 138);
insert into ingredienti (nome, piatto_id) values ('Vol Au Vents', 51);
insert into ingredienti (nome, piatto_id) values ('Soup - Knorr, Ministrone', 55);
insert into ingredienti (nome, piatto_id) values ('Cheese - Taleggio D.o.p.', 48);
insert into ingredienti (nome, piatto_id) values ('Peppercorns - Green', 87);
insert into ingredienti (nome, piatto_id) values ('Mix - Cocktail Ice Cream', 363);
insert into ingredienti (nome, piatto_id) values ('French Kiss Vanilla', 320);
insert into ingredienti (nome, piatto_id) values ('Flower - Carnations', 56);
insert into ingredienti (nome, piatto_id) values ('Cheese - St. Andre', 390);
insert into ingredienti (nome, piatto_id) values ('Juice - Lemon', 188);
insert into ingredienti (nome, piatto_id) values ('Pepsi - Diet, 355 Ml', 147);
insert into ingredienti (nome, piatto_id) values ('Tea - Herbal - 6 Asst', 68);
insert into ingredienti (nome, piatto_id) values ('Juice - Clam, 46 Oz', 26);
insert into ingredienti (nome, piatto_id) values ('Laundry - Bag Cloth', 371);
insert into ingredienti (nome, piatto_id) values ('Yogurt - Peach, 175 Gr', 60);
insert into ingredienti (nome, piatto_id) values ('Mushroom - Oyster, Fresh', 93);
insert into ingredienti (nome, piatto_id) values ('Otomegusa Dashi Konbu', 170);
insert into ingredienti (nome, piatto_id) values ('Propel Sport Drink', 387);
insert into ingredienti (nome, piatto_id) values ('Papayas', 331);
insert into ingredienti (nome, piatto_id) values ('Ice Cream - Chocolate', 363);
insert into ingredienti (nome, piatto_id) values ('Placemat - Scallop, White', 325);
insert into ingredienti (nome, piatto_id) values ('Nantucket - Pomegranate Pear', 127);
insert into ingredienti (nome, piatto_id) values ('Otomegusa Dashi Konbu', 317);
insert into ingredienti (nome, piatto_id) values ('Pan Grease', 328);
insert into ingredienti (nome, piatto_id) values ('Ham - Proscuitto', 154);
insert into ingredienti (nome, piatto_id) values ('Parsley Italian - Fresh', 375);
insert into ingredienti (nome, piatto_id) values ('Cheese - Havarti, Roasted Garlic', 273);
insert into ingredienti (nome, piatto_id) values ('Cheese - Bocconcini', 229);
insert into ingredienti (nome, piatto_id) values ('Foil Wrap', 142);
insert into ingredienti (nome, piatto_id) values ('Langers - Ruby Red Grapfruit', 387);
insert into ingredienti (nome, piatto_id) values ('Soup V8 Roasted Red Pepper', 379);
insert into ingredienti (nome, piatto_id) values ('Mackerel Whole Fresh', 279);
insert into ingredienti (nome, piatto_id) values ('Foam Cup 6 Oz', 323);
insert into ingredienti (nome, piatto_id) values ('Cookie - Oreo 100x2', 132);
insert into ingredienti (nome, piatto_id) values ('Apple - Royal Gala', 243);
insert into ingredienti (nome, piatto_id) values ('Milkettes - 2%', 229);
insert into ingredienti (nome, piatto_id) values ('Rosemary - Primerba, Paste', 186);
insert into ingredienti (nome, piatto_id) values ('Hersey Shakes', 326);
insert into ingredienti (nome, piatto_id) values ('Chocolate - Chips Compound', 196);
insert into ingredienti (nome, piatto_id) values ('Cheese - Grana Padano', 334);
insert into ingredienti (nome, piatto_id) values ('Beef - Ox Tail, Frozen', 130);
insert into ingredienti (nome, piatto_id) values ('Kellogs All Bran Bars', 113);
insert into ingredienti (nome, piatto_id) values ('Wine - Spumante Bambino White', 12);
insert into ingredienti (nome, piatto_id) values ('Couscous', 78);
insert into ingredienti (nome, piatto_id) values ('Tomatoes - Orange', 355);
insert into ingredienti (nome, piatto_id) values ('Pasta - Shells, Medium, Dry', 4);
insert into ingredienti (nome, piatto_id) values ('Thermometer Digital', 56);
insert into ingredienti (nome, piatto_id) values ('Cake - Box Window 10x10x2.5', 152);
insert into ingredienti (nome, piatto_id) values ('Buffalo - Short Rib Fresh', 210);
insert into ingredienti (nome, piatto_id) values ('Chicken - Livers', 178);
insert into ingredienti (nome, piatto_id) values ('Truffle Cups - White Paper', 47);
insert into ingredienti (nome, piatto_id) values ('Nutmeg - Ground', 388);
insert into ingredienti (nome, piatto_id) values ('Squash - Guords', 307);
insert into ingredienti (nome, piatto_id) values ('Nut - Peanut, Roasted', 329);
insert into ingredienti (nome, piatto_id) values ('Potatoes - Purple, Organic', 38);
insert into ingredienti (nome, piatto_id) values ('Buffalo - Short Rib Fresh', 66);
insert into ingredienti (nome, piatto_id) values ('Shrimp - 31/40', 256);
insert into ingredienti (nome, piatto_id) values ('Doilies - 5, Paper', 16);
insert into ingredienti (nome, piatto_id) values ('Wine - Magnotta - Red, Baco', 15);
insert into ingredienti (nome, piatto_id) values ('Tuna - Salad Premix', 136);
insert into ingredienti (nome, piatto_id) values ('Crackers - Water', 78);
insert into ingredienti (nome, piatto_id) values ('Cookies - Englishbay Chochip', 150);
insert into ingredienti (nome, piatto_id) values ('Broom - Push', 88);
insert into ingredienti (nome, piatto_id) values ('Tomatoes', 193);
insert into ingredienti (nome, piatto_id) values ('Nut - Hazelnut, Ground, Natural', 191);
insert into ingredienti (nome, piatto_id) values ('Dried Apple', 66);
insert into ingredienti (nome, piatto_id) values ('Pasta - Rotini, Colour, Dry', 174);
insert into ingredienti (nome, piatto_id) values ('Island Oasis - Sweet And Sour Mix', 251);
insert into ingredienti (nome, piatto_id) values ('Glass Clear 7 Oz Xl', 154);
insert into ingredienti (nome, piatto_id) values ('Apple - Custard', 113);
insert into ingredienti (nome, piatto_id) values ('Sprouts - Pea', 310);
insert into ingredienti (nome, piatto_id) values ('Jolt Cola', 44);
insert into ingredienti (nome, piatto_id) values ('Petite Baguette', 119);
insert into ingredienti (nome, piatto_id) values ('Beef - Roasted, Cooked', 346);
insert into ingredienti (nome, piatto_id) values ('Lemon Balm - Fresh', 41);
insert into ingredienti (nome, piatto_id) values ('Cakes Assorted', 267);
insert into ingredienti (nome, piatto_id) values ('Pastry - Lemon Danish - Mini', 200);
insert into ingredienti (nome, piatto_id) values ('Cream - 10%', 347);
insert into ingredienti (nome, piatto_id) values ('Hagen Daza - Dk Choocolate', 332);
insert into ingredienti (nome, piatto_id) values ('Lettuce - Belgian Endive', 303);
insert into ingredienti (nome, piatto_id) values ('Butter Sweet', 93);
insert into ingredienti (nome, piatto_id) values ('Milk Powder', 7);
insert into ingredienti (nome, piatto_id) values ('Arctic Char - Fresh, Whole', 226);
insert into ingredienti (nome, piatto_id) values ('Pasta - Fett Alfredo, Single Serve', 278);
insert into ingredienti (nome, piatto_id) values ('Vinegar - White', 346);
insert into ingredienti (nome, piatto_id) values ('Kippers - Smoked', 129);
insert into ingredienti (nome, piatto_id) values ('Arizona - Green Tea', 328);
insert into ingredienti (nome, piatto_id) values ('Pasta - Lasagna Noodle, Frozen', 385);
insert into ingredienti (nome, piatto_id) values ('Cheese Cheddar Processed', 205);
insert into ingredienti (nome, piatto_id) values ('C - Plus, Orange', 100);
insert into ingredienti (nome, piatto_id) values ('Bread Foccacia Whole', 112);
insert into ingredienti (nome, piatto_id) values ('Eggplant - Baby', 218);
insert into ingredienti (nome, piatto_id) values ('Beer - True North Lager', 109);
insert into ingredienti (nome, piatto_id) values ('Wine - Red, Lurton Merlot De', 110);
insert into ingredienti (nome, piatto_id) values ('Stock - Chicken, White', 11);
insert into ingredienti (nome, piatto_id) values ('Wine - Red, Black Opal Shiraz', 322);
insert into ingredienti (nome, piatto_id) values ('Trout Rainbow Whole', 210);
insert into ingredienti (nome, piatto_id) values ('Mountain Dew', 111);
insert into ingredienti (nome, piatto_id) values ('Melon - Watermelon, Seedless', 172);
insert into ingredienti (nome, piatto_id) values ('Lamb - Shoulder, Boneless', 244);
insert into ingredienti (nome, piatto_id) values ('Greens Mustard', 149);
insert into ingredienti (nome, piatto_id) values ('Milk - Chocolate 250 Ml', 127);
insert into ingredienti (nome, piatto_id) values ('Lobster - Baby, Boiled', 96);
insert into ingredienti (nome, piatto_id) values ('Piping - Bags Quizna', 184);
insert into ingredienti (nome, piatto_id) values ('Scallops 60/80 Iqf', 364);
insert into ingredienti (nome, piatto_id) values ('Tofu - Soft', 188);
insert into ingredienti (nome, piatto_id) values ('Icecream Bar - Del Monte', 303);
insert into ingredienti (nome, piatto_id) values ('Cup - Paper 10oz 92959', 118);
insert into ingredienti (nome, piatto_id) values ('Wiberg Super Cure', 108);
insert into ingredienti (nome, piatto_id) values ('Edible Flower - Mixed', 145);
insert into ingredienti (nome, piatto_id) values ('Nestea - Ice Tea, Diet', 115);
insert into ingredienti (nome, piatto_id) values ('Beef - Cooked, Corned', 362);
insert into ingredienti (nome, piatto_id) values ('Syrup - Kahlua Chocolate', 140);
insert into ingredienti (nome, piatto_id) values ('Versatainer Nc - 8288', 320);
insert into ingredienti (nome, piatto_id) values ('Soup - French Onion, Dry', 24);
insert into ingredienti (nome, piatto_id) values ('Horseradish Root', 63);
insert into ingredienti (nome, piatto_id) values ('Pepper - Green Thai', 377);
insert into ingredienti (nome, piatto_id) values ('Wakami Seaweed', 87);
insert into ingredienti (nome, piatto_id) values ('Tequila - Sauza Silver', 283);
insert into ingredienti (nome, piatto_id) values ('Irish Cream - Baileys', 176);
insert into ingredienti (nome, piatto_id) values ('Truffle Cups - Brown', 116);
insert into ingredienti (nome, piatto_id) values ('7up Diet, 355 Ml', 138);
insert into ingredienti (nome, piatto_id) values ('Island Oasis - Wildberry', 241);
insert into ingredienti (nome, piatto_id) values ('Doilies - 10, Paper', 57);
insert into ingredienti (nome, piatto_id) values ('Chocolate - Milk', 294);
insert into ingredienti (nome, piatto_id) values ('Bread - 10 Grain Parisian', 24);
insert into ingredienti (nome, piatto_id) values ('Thyme - Lemon, Fresh', 67);
insert into ingredienti (nome, piatto_id) values ('Cheese - Oka', 352);
insert into ingredienti (nome, piatto_id) values ('Duck - Fat', 230);
insert into ingredienti (nome, piatto_id) values ('Extract - Raspberry', 76);
insert into ingredienti (nome, piatto_id) values ('Bag - Bread, White, Plain', 32);
insert into ingredienti (nome, piatto_id) values ('Green Scrubbie Pad H.duty', 246);
insert into ingredienti (nome, piatto_id) values ('Pepper - Chili Powder', 252);
insert into ingredienti (nome, piatto_id) values ('Juice - Prune', 86);
insert into ingredienti (nome, piatto_id) values ('Lobster - Tail, 3 - 4 Oz', 174);
insert into ingredienti (nome, piatto_id) values ('Beef - Top Butt', 380);
insert into ingredienti (nome, piatto_id) values ('Chinese Foods - Plain Fried Rice', 13);
insert into ingredienti (nome, piatto_id) values ('Table Cloth 62x114 White', 221);
insert into ingredienti (nome, piatto_id) values ('Sole - Dover, Whole, Fresh', 367);
insert into ingredienti (nome, piatto_id) values ('Pear - Prickly', 229);
insert into ingredienti (nome, piatto_id) values ('Nantucket - Pomegranate Pear', 197);
insert into ingredienti (nome, piatto_id) values ('Spoon - Soup, Plastic', 157);
insert into ingredienti (nome, piatto_id) values ('Spice - Onion Powder Granulated', 80);
insert into ingredienti (nome, piatto_id) values ('Pork - Bacon, Double Smoked', 45);
insert into ingredienti (nome, piatto_id) values ('Veal - Nuckle', 146);
insert into ingredienti (nome, piatto_id) values ('Chocolate Bar - Oh Henry', 337);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Riesling, Semi - Dry', 267);
insert into ingredienti (nome, piatto_id) values ('Cookies - Amaretto', 227);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Pelee Island', 170);
insert into ingredienti (nome, piatto_id) values ('Chicken - White Meat With Tender', 75);
insert into ingredienti (nome, piatto_id) values ('Calypso - Strawberry Lemonade', 246);
insert into ingredienti (nome, piatto_id) values ('Pepper - Roasted Red', 338);
insert into ingredienti (nome, piatto_id) values ('Ice Cream Bar - Oreo Cone', 144);
insert into ingredienti (nome, piatto_id) values ('Skewers - Bamboo', 318);
insert into ingredienti (nome, piatto_id) values ('Egg - Salad Premix', 186);
insert into ingredienti (nome, piatto_id) values ('Flour - Pastry', 127);
insert into ingredienti (nome, piatto_id) values ('Table Cloth 54x72 White', 394);
insert into ingredienti (nome, piatto_id) values ('Wine - Kwv Chenin Blanc South', 113);
insert into ingredienti (nome, piatto_id) values ('Turnip - White', 124);
insert into ingredienti (nome, piatto_id) values ('Bay Leaf Fresh', 76);
insert into ingredienti (nome, piatto_id) values ('Chick Peas - Canned', 51);
insert into ingredienti (nome, piatto_id) values ('Cheese - Parmigiano Reggiano', 161);
insert into ingredienti (nome, piatto_id) values ('Shrimp - 16 - 20 Cooked, Peeled', 398);
insert into ingredienti (nome, piatto_id) values ('Venison - Striploin', 64);
insert into ingredienti (nome, piatto_id) values ('Juice - Ocean Spray Cranberry', 390);
insert into ingredienti (nome, piatto_id) values ('Pop - Club Soda Can', 155);
insert into ingredienti (nome, piatto_id) values ('Fenngreek Seed', 55);
insert into ingredienti (nome, piatto_id) values ('Lemon Balm - Fresh', 109);
insert into ingredienti (nome, piatto_id) values ('Madeira', 157);
insert into ingredienti (nome, piatto_id) values ('Mushroom - Portebello', 252);
insert into ingredienti (nome, piatto_id) values ('Chervil - Fresh', 338);
insert into ingredienti (nome, piatto_id) values ('Energy Drink - Franks Pineapple', 288);
insert into ingredienti (nome, piatto_id) values ('Syrup - Monin - Passion Fruit', 376);
insert into ingredienti (nome, piatto_id) values ('Sausage - Chorizo', 85);
insert into ingredienti (nome, piatto_id) values ('Miso - Soy Bean Paste', 39);
insert into ingredienti (nome, piatto_id) values ('Quail - Jumbo', 344);
insert into ingredienti (nome, piatto_id) values ('Nutmeg - Ground', 14);
insert into ingredienti (nome, piatto_id) values ('Wine - Niagara Peninsula Vqa', 227);
insert into ingredienti (nome, piatto_id) values ('Grouper - Fresh', 287);
insert into ingredienti (nome, piatto_id) values ('Cheese - Provolone', 398);
insert into ingredienti (nome, piatto_id) values ('Wine - Jackson Triggs Okonagan', 378);
insert into ingredienti (nome, piatto_id) values ('Port - 74 Brights', 164);
insert into ingredienti (nome, piatto_id) values ('Muffin - Mix - Creme Brule 15l', 254);
insert into ingredienti (nome, piatto_id) values ('Bread - Pita', 201);
insert into ingredienti (nome, piatto_id) values ('Prunes - Pitted', 305);
insert into ingredienti (nome, piatto_id) values ('Silicone Paper 16.5x24', 178);
insert into ingredienti (nome, piatto_id) values ('Lychee', 310);
insert into ingredienti (nome, piatto_id) values ('Toothpick Frilled', 272);
insert into ingredienti (nome, piatto_id) values ('Scallop - St. Jaques', 225);
insert into ingredienti (nome, piatto_id) values ('Beer - Heinekin', 274);
insert into ingredienti (nome, piatto_id) values ('Tomatoes - Yellow Hot House', 195);
insert into ingredienti (nome, piatto_id) values ('Cheese - Cheddar, Medium', 318);
insert into ingredienti (nome, piatto_id) values ('Flour - Buckwheat, Dark', 85);
insert into ingredienti (nome, piatto_id) values ('Sugar - Fine', 91);
insert into ingredienti (nome, piatto_id) values ('Jam - Raspberry,jar', 151);
insert into ingredienti (nome, piatto_id) values ('Napkin White - Starched', 193);
insert into ingredienti (nome, piatto_id) values ('Eggplant - Regular', 53);
insert into ingredienti (nome, piatto_id) values ('Ice Cream - Chocolate', 285);
insert into ingredienti (nome, piatto_id) values ('Syrup - Monin - Passion Fruit', 86);
insert into ingredienti (nome, piatto_id) values ('Wine - Dubouef Macon - Villages', 266);
insert into ingredienti (nome, piatto_id) values ('Salmon - Atlantic, No Skin', 45);
insert into ingredienti (nome, piatto_id) values ('Mcgillicuddy Vanilla Schnap', 279);
insert into ingredienti (nome, piatto_id) values ('Cabbage - Red', 221);
insert into ingredienti (nome, piatto_id) values ('Beer - Muskoka Cream Ale', 210);
insert into ingredienti (nome, piatto_id) values ('Numi - Assorted Teas', 279);
insert into ingredienti (nome, piatto_id) values ('Syrup - Kahlua Chocolate', 375);
insert into ingredienti (nome, piatto_id) values ('Wine - Chardonnay South', 240);
insert into ingredienti (nome, piatto_id) values ('Veal - Ground', 322);
insert into ingredienti (nome, piatto_id) values ('Yeast Dry - Fermipan', 5);
insert into ingredienti (nome, piatto_id) values ('Lemon Pepper', 131);
insert into ingredienti (nome, piatto_id) values ('Muffin Batt - Blueberry Passion', 221);
insert into ingredienti (nome, piatto_id) values ('Pickerel - Fillets', 329);
insert into ingredienti (nome, piatto_id) values ('Toamtoes 6x7 Select', 219);
insert into ingredienti (nome, piatto_id) values ('Beer - Pilsner Urquell', 252);
insert into ingredienti (nome, piatto_id) values ('Lamb Rack Frenched Australian', 338);
insert into ingredienti (nome, piatto_id) values ('Mushroom - King Eryingii', 143);
insert into ingredienti (nome, piatto_id) values ('Beef - Tongue, Fresh', 53);
insert into ingredienti (nome, piatto_id) values ('Wine - Saint Emilion Calvet', 184);
insert into ingredienti (nome, piatto_id) values ('Lettuce - Green Leaf', 84);
insert into ingredienti (nome, piatto_id) values ('Nantuket Peach Orange', 157);
insert into ingredienti (nome, piatto_id) values ('Bread - Petit Baguette', 223);
insert into ingredienti (nome, piatto_id) values ('Bread Base - Goodhearth', 232);
insert into ingredienti (nome, piatto_id) values ('Vinegar - Balsamic, White', 194);
insert into ingredienti (nome, piatto_id) values ('Port - 74 Brights', 13);
insert into ingredienti (nome, piatto_id) values ('Shrimp - Baby, Cold Water', 31);
insert into ingredienti (nome, piatto_id) values ('Tea - Lemon Green Tea', 40);
insert into ingredienti (nome, piatto_id) values ('Bread - French Stick', 397);
insert into ingredienti (nome, piatto_id) values ('Marjoram - Dried, Rubbed', 44);
insert into ingredienti (nome, piatto_id) values ('Crab - Claws, Snow 16 - 24', 168);
insert into ingredienti (nome, piatto_id) values ('Turkey Leg With Drum And Thigh', 211);
insert into ingredienti (nome, piatto_id) values ('Wine - Chablis 2003 Champs', 285);
insert into ingredienti (nome, piatto_id) values ('Chips Potato All Dressed - 43g', 372);
insert into ingredienti (nome, piatto_id) values ('Flour - Bran, Red', 363);
insert into ingredienti (nome, piatto_id) values ('Sausage - Chorizo', 1);
insert into ingredienti (nome, piatto_id) values ('Capon - Whole', 188);
insert into ingredienti (nome, piatto_id) values ('Pork Casing', 221);
insert into ingredienti (nome, piatto_id) values ('Cookie Dough - Double', 184);
insert into ingredienti (nome, piatto_id) values ('Soup Bowl Clear 8oz92008', 232);
insert into ingredienti (nome, piatto_id) values ('Pastry - Mini French Pastries', 310);
insert into ingredienti (nome, piatto_id) values ('Sage - Rubbed', 27);
insert into ingredienti (nome, piatto_id) values ('Tofu - Soft', 173);
insert into ingredienti (nome, piatto_id) values ('Pasta - Lasagne, Fresh', 291);
insert into ingredienti (nome, piatto_id) values ('Wine - Mas Chicet Rose, Vintage', 294);
insert into ingredienti (nome, piatto_id) values ('Wine - Gewurztraminer Pierre', 322);
insert into ingredienti (nome, piatto_id) values ('Wine - Chablis 2003 Champs', 211);
insert into ingredienti (nome, piatto_id) values ('Meldea Green Tea Liquor', 68);
insert into ingredienti (nome, piatto_id) values ('Shrimp - Black Tiger 26/30', 288);
insert into ingredienti (nome, piatto_id) values ('Mustard - Individual Pkg', 73);
insert into ingredienti (nome, piatto_id) values ('Lamb Leg - Bone - In Nz', 10);
insert into ingredienti (nome, piatto_id) values ('Turnip - Wax', 213);
insert into ingredienti (nome, piatto_id) values ('Wine - Champagne Brut Veuve', 188);
insert into ingredienti (nome, piatto_id) values ('Milk - Condensed', 302);
insert into ingredienti (nome, piatto_id) values ('Buttons', 381);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Gewurtzraminer', 96);
insert into ingredienti (nome, piatto_id) values ('Contreau', 391);
insert into ingredienti (nome, piatto_id) values ('Bread - Raisin Walnut Pull', 161);
insert into ingredienti (nome, piatto_id) values ('Anchovy Fillets', 229);
insert into ingredienti (nome, piatto_id) values ('Compound - Strawberry', 282);
insert into ingredienti (nome, piatto_id) values ('Lid Coffee Cup 8oz Blk', 208);
insert into ingredienti (nome, piatto_id) values ('Bag Clear 10 Lb', 287);
insert into ingredienti (nome, piatto_id) values ('Grenadine', 347);
insert into ingredienti (nome, piatto_id) values ('Currants', 226);
insert into ingredienti (nome, piatto_id) values ('Ice Cream Bar - Oreo Sandwich', 23);
insert into ingredienti (nome, piatto_id) values ('Lamb - Bones', 2);
insert into ingredienti (nome, piatto_id) values ('Vaccum Bag 10x13', 57);
insert into ingredienti (nome, piatto_id) values ('Sprouts - Pea', 165);
insert into ingredienti (nome, piatto_id) values ('Turkey Tenderloin Frozen', 236);
insert into ingredienti (nome, piatto_id) values ('Cheese - Provolone', 83);
insert into ingredienti (nome, piatto_id) values ('Croissants Thaw And Serve', 56);
insert into ingredienti (nome, piatto_id) values ('Puree - Mocha', 347);
insert into ingredienti (nome, piatto_id) values ('Rum - Coconut, Malibu', 377);
insert into ingredienti (nome, piatto_id) values ('Lid - 0090 Clear', 46);
insert into ingredienti (nome, piatto_id) values ('Pepper - Roasted Red', 292);
insert into ingredienti (nome, piatto_id) values ('Beef - Sushi Flat Iron Steak', 115);
insert into ingredienti (nome, piatto_id) values ('Wine - Prosecco Valdobiaddene', 285);
insert into ingredienti (nome, piatto_id) values ('Doilies - 8, Paper', 146);
insert into ingredienti (nome, piatto_id) values ('Rabbit - Saddles', 76);
insert into ingredienti (nome, piatto_id) values ('Noodles - Steamed Chow Mein', 337);
insert into ingredienti (nome, piatto_id) values ('Foil - Round Foil', 245);
insert into ingredienti (nome, piatto_id) values ('Taro Leaves', 257);
insert into ingredienti (nome, piatto_id) values ('Tomatoes - Diced, Canned', 147);
insert into ingredienti (nome, piatto_id) values ('Coffee - Irish Cream', 200);
insert into ingredienti (nome, piatto_id) values ('Wine - Cousino Macul Antiguas', 108);
insert into ingredienti (nome, piatto_id) values ('Mix Pina Colada', 30);
insert into ingredienti (nome, piatto_id) values ('Wine - Red, Colio Cabernet', 164);
insert into ingredienti (nome, piatto_id) values ('Tortillas - Flour, 10', 271);
insert into ingredienti (nome, piatto_id) values ('Lid Coffeecup 12oz D9542b', 319);
insert into ingredienti (nome, piatto_id) values ('Lamb - Loin, Trimmed, Boneless', 312);
insert into ingredienti (nome, piatto_id) values ('Vaccum Bag 10x13', 130);
insert into ingredienti (nome, piatto_id) values ('Garam Masala Powder', 252);
insert into ingredienti (nome, piatto_id) values ('Evaporated Milk - Skim', 294);
insert into ingredienti (nome, piatto_id) values ('Soup - Cream Of Broccoli, Dry', 115);
insert into ingredienti (nome, piatto_id) values ('Pork - Liver', 159);
insert into ingredienti (nome, piatto_id) values ('Soup - Campbellschix Stew', 142);
insert into ingredienti (nome, piatto_id) values ('Brandy Cherry - Mcguinness', 161);
insert into ingredienti (nome, piatto_id) values ('Horseradish - Prepared', 246);
insert into ingredienti (nome, piatto_id) values ('Yokaline', 189);
insert into ingredienti (nome, piatto_id) values ('Lobster - Tail, 3 - 4 Oz', 15);
insert into ingredienti (nome, piatto_id) values ('Longos - Burritos', 244);
insert into ingredienti (nome, piatto_id) values ('Soup - Cream Of Broccoli, Dry', 105);
insert into ingredienti (nome, piatto_id) values ('Bread - Sour Batard', 126);
insert into ingredienti (nome, piatto_id) values ('Plastic Wrap', 205);
insert into ingredienti (nome, piatto_id) values ('Flower - Potmums', 158);
insert into ingredienti (nome, piatto_id) values ('Mint - Fresh', 257);
insert into ingredienti (nome, piatto_id) values ('Cinnamon - Stick', 372);
insert into ingredienti (nome, piatto_id) values ('Pasta - Fusili Tri - Coloured', 59);
insert into ingredienti (nome, piatto_id) values ('Tart Shells - Sweet, 3', 90);
insert into ingredienti (nome, piatto_id) values ('Wine - Black Tower Qr', 48);
insert into ingredienti (nome, piatto_id) values ('Cheese - Brie, Triple Creme', 55);
insert into ingredienti (nome, piatto_id) values ('Muffin - Mix - Creme Brule 15l', 322);
insert into ingredienti (nome, piatto_id) values ('Cheese - Gouda', 235);
insert into ingredienti (nome, piatto_id) values ('Arrowroot', 263);
insert into ingredienti (nome, piatto_id) values ('Pasta - Gnocchi, Potato', 285);
insert into ingredienti (nome, piatto_id) values ('Sobe - Orange Carrot', 194);
insert into ingredienti (nome, piatto_id) values ('Cheese - Brick With Pepper', 30);
insert into ingredienti (nome, piatto_id) values ('Garam Masala Powder', 316);
insert into ingredienti (nome, piatto_id) values ('Otomegusa Dashi Konbu', 231);
insert into ingredienti (nome, piatto_id) values ('Ice - Clear, 300 Lb For Carving', 169);
insert into ingredienti (nome, piatto_id) values ('Mackerel Whole Fresh', 244);
insert into ingredienti (nome, piatto_id) values ('Apple - Royal Gala', 386);
insert into ingredienti (nome, piatto_id) values ('Chocolate Bar - Reese Pieces', 400);
insert into ingredienti (nome, piatto_id) values ('Anchovy Fillets', 392);
insert into ingredienti (nome, piatto_id) values ('Juice - Mango', 171);
insert into ingredienti (nome, piatto_id) values ('Wine - Jaboulet Cotes Du Rhone', 251);
insert into ingredienti (nome, piatto_id) values ('Butter - Salted, Micro', 312);
insert into ingredienti (nome, piatto_id) values ('Cookies - Assorted', 134);
insert into ingredienti (nome, piatto_id) values ('Nori Sea Weed', 71);
insert into ingredienti (nome, piatto_id) values ('Wine - Clavet Saint Emilion', 111);
insert into ingredienti (nome, piatto_id) values ('Wine - German Riesling', 202);
insert into ingredienti (nome, piatto_id) values ('Filo Dough', 220);
insert into ingredienti (nome, piatto_id) values ('Cabbage - Green', 367);
insert into ingredienti (nome, piatto_id) values ('Tarragon - Fresh', 391);
insert into ingredienti (nome, piatto_id) values ('Flour - All Purpose', 378);
insert into ingredienti (nome, piatto_id) values ('Pail With Metal Handle 16l White', 347);
insert into ingredienti (nome, piatto_id) values ('Coffee - Frthy Coffee Crisp', 216);
insert into ingredienti (nome, piatto_id) values ('Pie Shell - 5', 334);
insert into ingredienti (nome, piatto_id) values ('Sprite, Diet - 355ml', 397);
insert into ingredienti (nome, piatto_id) values ('Chinese Foods - Chicken Wing', 259);
insert into ingredienti (nome, piatto_id) values ('Vinegar - White Wine', 349);
insert into ingredienti (nome, piatto_id) values ('Baking Soda', 245);
insert into ingredienti (nome, piatto_id) values ('Eggplant - Asian', 5);
insert into ingredienti (nome, piatto_id) values ('Quail - Eggs, Fresh', 76);
insert into ingredienti (nome, piatto_id) values ('Pastry - Lemon Danish - Mini', 2);
insert into ingredienti (nome, piatto_id) values ('Duck - Fat', 335);
insert into ingredienti (nome, piatto_id) values ('Chocolate - Liqueur Cups With Foil', 320);
insert into ingredienti (nome, piatto_id) values ('Chips Potato Reg 43g', 168);
insert into ingredienti (nome, piatto_id) values ('Muffin Mix - Corn Harvest', 108);
insert into ingredienti (nome, piatto_id) values ('Flavouring Vanilla Artificial', 113);
insert into ingredienti (nome, piatto_id) values ('Muffin Mix - Morning Glory', 122);
insert into ingredienti (nome, piatto_id) values ('Beef - Top Butt', 329);
insert into ingredienti (nome, piatto_id) values ('Munchies Honey Sweet Trail Mix', 334);
insert into ingredienti (nome, piatto_id) values ('Crackers - Melba Toast', 155);
insert into ingredienti (nome, piatto_id) values ('Sprite, Diet - 355ml', 390);
insert into ingredienti (nome, piatto_id) values ('Amarula Cream', 148);
insert into ingredienti (nome, piatto_id) values ('Bread Foccacia Whole', 254);
insert into ingredienti (nome, piatto_id) values ('Wine - Jaboulet Cotes Du Rhone', 392);
insert into ingredienti (nome, piatto_id) values ('Myers Planters Punch', 210);
insert into ingredienti (nome, piatto_id) values ('Pimento - Canned', 175);
insert into ingredienti (nome, piatto_id) values ('Jolt Cola', 342);
insert into ingredienti (nome, piatto_id) values ('Noodles - Cellophane, Thin', 154);
insert into ingredienti (nome, piatto_id) values ('Rabbit - Saddles', 242);
insert into ingredienti (nome, piatto_id) values ('Puree - Passion Fruit', 19);
insert into ingredienti (nome, piatto_id) values ('Beans - Kidney White', 129);
insert into ingredienti (nome, piatto_id) values ('Crab - Dungeness, Whole', 285);
insert into ingredienti (nome, piatto_id) values ('Bagel - Everything Presliced', 263);
insert into ingredienti (nome, piatto_id) values ('Beans - French', 15);
insert into ingredienti (nome, piatto_id) values ('Zucchini - Yellow', 38);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Mosel Gold', 252);
insert into ingredienti (nome, piatto_id) values ('Beef - Top Butt', 7);
insert into ingredienti (nome, piatto_id) values ('Tart - Lemon', 264);
insert into ingredienti (nome, piatto_id) values ('Canadian Emmenthal', 136);
insert into ingredienti (nome, piatto_id) values ('Wine - White Cab Sauv.on', 88);
insert into ingredienti (nome, piatto_id) values ('Vinegar - Champagne', 361);
insert into ingredienti (nome, piatto_id) values ('Bread - Pumpernickel', 375);
insert into ingredienti (nome, piatto_id) values ('Soup - Boston Clam Chowder', 299);
insert into ingredienti (nome, piatto_id) values ('Wine - Winzer Krems Gruner', 170);
insert into ingredienti (nome, piatto_id) values ('Wine - Sauvignon Blanc', 81);
insert into ingredienti (nome, piatto_id) values ('Apples - Sliced / Wedge', 321);
insert into ingredienti (nome, piatto_id) values ('Cheese - Le Cru Du Clocher', 311);
insert into ingredienti (nome, piatto_id) values ('Soup - Campbells - Tomato', 21);
insert into ingredienti (nome, piatto_id) values ('Flavouring - Rum', 190);
insert into ingredienti (nome, piatto_id) values ('Sugar - Invert', 81);
insert into ingredienti (nome, piatto_id) values ('Cherries - Maraschino,jar', 343);
insert into ingredienti (nome, piatto_id) values ('Vermouth - Sweet, Cinzano', 226);
insert into ingredienti (nome, piatto_id) values ('Chips Potato Swt Chilli Sour', 312);
insert into ingredienti (nome, piatto_id) values ('Cumin - Ground', 318);
insert into ingredienti (nome, piatto_id) values ('Juice - Orangina', 382);
insert into ingredienti (nome, piatto_id) values ('Beef - Bones, Cut - Up', 93);
insert into ingredienti (nome, piatto_id) values ('Tahini Paste', 150);
insert into ingredienti (nome, piatto_id) values ('Cleaner - Pine Sol', 269);
insert into ingredienti (nome, piatto_id) values ('Initation Crab Meat', 190);
insert into ingredienti (nome, piatto_id) values ('Pork - Hock And Feet Attached', 176);
insert into ingredienti (nome, piatto_id) values ('Pork - Back Ribs', 86);
insert into ingredienti (nome, piatto_id) values ('Juice - Lemon', 333);
insert into ingredienti (nome, piatto_id) values ('Bread - Raisin Walnut Oval', 217);
insert into ingredienti (nome, piatto_id) values ('Soup - Clam Chowder, Dry Mix', 70);
insert into ingredienti (nome, piatto_id) values ('Durian Fruit', 358);
insert into ingredienti (nome, piatto_id) values ('Wine - White, Concha Y Toro', 191);
